### ISSUE TITLE
Add render_form to jinja2

### ISSUE THREAD

**Issue by nirgn975** [encode/apistar#180]
When I'm trying to use `render_form` in the template like this:
```
<html>
    <body>
        <h1>{{ message }}</h1>
        {{ render_form('https://google.com') }}
    </body>
</html>
```

I get an error message:
<img width="787" alt="jinja2_exceptions_undefinederror___render_form__is_undefined____werkzeug_debugger" src="https://cloud.githubusercontent.com/assets/3472902/26384435/0a559d82-3fee-11e7-9426-f84e2293c89a.png">

What I'm doing wrong? (haven't change anything yet)

**Comment by tomchristie** [comment]
`render_form` doesn't exist by default in the templates, but does get included explicitly by the docs template. And yes, we need to add a bunch of globally available template functions in due course, including `render_form`, `static`, and `reverse_url`

**Comment by isaevpd** [comment]
I can probably pick this up, will check on the weekend how this works.

**Comment by pavelholvi** [comment]
Hey, so `static` is supposed to do same thing as it does for example in django, `reverse_url` would be equivalent of `url` in django, and how is `render_form` supposed to work exactly? For example with `https://google.com`?

Sorry for using different github accounts here.

what would be the approach? I'm a bit at loss here. Is it something similar to how it's done in django?

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
