### ISSUE TITLE
Allow arguments for backend commands

### ISSUE THREAD

**Issue by mammuth** [encode/apistar#191]
I love that the django backend is (being) implemented!

So it looks like the commands (_migrate, makemigrations_ and _showmigrations_) are hardcoded in the backend component via `django.core.management.call_command`. 
As a result it's currently not possible to add parameters or options to the commands like eg. `apistar makemigrations --dry-run`.

Those possible arguments should probably be supported in a generic way for all commands of various backends, shouldn't it?

**Comment by tomchristie** [comment]
> Those possible arguments should probably be supported in a generic way for all commands of various backends, shouldn't it?

Absolutely, yup!

**Comment by tomchristie** [comment]
Let's close this off at the moment, as it's not currently relevant given the 0.4 re-write.
