### ISSUE TITLE
Error running on Windows 7

### ISSUE THREAD

**Issue by jglasgow3** [encode/apistar#207]
Trying the command "apistar run" generates the following error:
Starting up...
 * Restarting with stat
  File "c:\users\jglasgow\Wicked_Lemur\Scripts\apistar.exe", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file \Scripts\apistar.exe on line 1, but no encoding decla
red; see http://python.org/dev/peps/pep-0263/ for details

**Comment by audiolion** [comment]
how did you install it? seems to be related to #196

**Comment by jglasgow3** [comment]
I did pip install apistar from a python 3.6.1 virtualenv.

**Comment by androiddrew** [comment]
I am encountering the same issue.

**Comment by ab95david** [comment]
Me too, I'm running it on Windows 10.

**Comment by tomchristie** [comment]
Folding this into #208.
