### ISSUE TITLE
Integrating `schema.description` with docs?

### ISSUE THREAD

**Issue by GeoTob** [encode/apistar#211]
Is there a way to populate the `description` column for each field in the automatically generated docs:

![documentation](https://github.com/tomchristie/apistar/raw/master/docs/img/apistar.png)

I have tried to use a custom schema like below without any success:
```python
class Name(schema.String):
    description = 'Name for greeting'


def greet(name:Name):
    ...
```

**Comment by tomchristie** [comment]
Yup, that's intended but hasn't made it's way in yet.

**Comment by aidiss** [comment]
How can  I add it manually?

**Comment by audiolion** [comment]
@aidiss fork the repo and add it in manually, or make a PR to this library to add support for it

**Comment by ssteinerx** [comment]
Is the intention to support `description` via custom schema as shown by @GeoTob or some other method?  

Also, will e.g. `default` be able to be set and used in a similar manner?

**Comment by tomchristie** [comment]
I'm going to close this off, since we don't have the docs back in yet, *but* worth noting that the redesigned type system *does* support `description=...` on the validators, which we'll use to pull this info in, once we've got the redesigned docs going.
