### ISSUE TITLE
Sentry integration

### ISSUE THREAD

**Issue by Gr1N** [encode/apistar#215]
Hi, 

Thanks for the project, it looks very interesting! But I would like to know how can I integrate sentry into apistar? Of course I can write decorator and wrap all views but its looks too complex... and this question not only about sentry, there are a common question how to wrap all views in project? There are no middlewares for this and I don't think that I can implement everything using only components.

**Comment by tomchristie** [comment]
Your best option at the moment would be to use WSGI middleware. Aware that we need a better solution to that too, but needs thinking about because the model that we have isn't quite a standard req/resp style that we can fit middleware around, so we may need a different approach.

**Comment by Gr1N** [comment]
Thanks, but this is not an answer I'd like to hear :) 
Maybe you have any plans or ideas how it can be implemented in apistar (except WSGI middlewares)?

**Comment by Gr1N** [comment]
And as I understand any decorator on view will broke components injection? Please fix me if I'm wrong.

**Comment by wuub** [comment]
Just wanted to add my $0.02 :)

I did some very initial work, and it seems that a hack like show below has some promise.  But it's not battle tested in any way and not complete. 

```python
class SentryEventID(str):
    pass

def raven_exception_handler(response: wsgi.WSGIResponse, environ: wsgi.WSGIEnviron, exc: Exception) -> SentryEventID:
     result = raven_client.captureException(exc_info=sys.exc_info())
     # this is only an example, I tried to modify response to include X-Sentry-ID in response 
     # headers, but something is overwriting it :)
     if result:
         return SentryEventID(result)
     return SentryEventID(-1)


pipeline = build_pipeline(raven_exception_handler, [http.Response, wsgi.WSGIEnviron, Exception], SentryEventID, {})
app.router.exception_pipeline.append(pipeline[0])
```

**Comment by tomchristie** [comment]
Sentry provide WSGI middleware for exactly this purpose... https://docs.sentry.io/clients/python/integrations/wsgi/

I'm also planning on targeting flask and django as framework options, so that'll be an alternative route.

How we'll tackle something like middleware is still an open question, since the dependency injection style is rather different from the typically request/response, so it's less obvious how we'd want to tackle that.

**Comment by vascop** [comment]
Using the middleware as described in the Sentry docs results in the exception below due to the type check in https://github.com/encode/apistar/blob/master/apistar/main.py#L22:
`apistar.exceptions.ConfigurationError: The 'app' variable in 'app.py' is not an App instance.`

**Comment by audiolion** [comment]
this can probably be closed off, use something like [apistar_sentry](https://github.com/Bogdanp/apistar_sentry) or roll your own with event hooks

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
