### ISSUE TITLE
could it return {"error": "exception "} instead of entering the debugger?

### ISSUE THREAD

**Issue by kootenpv** [encode/apistar#219]
e.g.:

`{"error": "ValueError: invalid literal for int() with base 10: 'a'"}`

At least this is what I would expect if not in debugging mode...

**Comment by tomchristie** [comment]
Yup we'll absolutely want to have more finessed error handling behavior between development and production. Gets better to an extent in https://github.com/tomchristie/apistar/pull/235 since the exception handler is then easily overridable on the `App`.
