### ISSUE TITLE
How to create endpoints like in the example given in the presentation?

### ISSUE THREAD

**Issue by aidiss** [encode/apistar#221]
![image](https://user-images.githubusercontent.com/5175311/27770170-852b66c2-5f42-11e7-8422-8172441d0fc5.png)
kittens
  - list_favorite_kittens
  - add_favorite_kitten
petstore

**Comment by tomchristie** [comment]
The sectioning isn't yet supported, tho it is planned.

**Comment by tomchristie** [comment]
We'll be re-introducing the API docs in due course. Given that they've currently been removed we may as well close this off for now. (And yes it's a bit painful, but the reworking has absolutely been needed)
