### ISSUE TITLE
CLI Sub-Commands 

### ISSUE THREAD

**Issue by jwbixby** [encode/apistar#236]
Obviously no ones top priority currently, but I was playing around a bit and got a pretty simple MVP of sub-commands(nested commands) working. Please let me know if this is a feature that you'd like to see in apistar. If it is, I'll clean this up and write some tests.

https://github.com/jwbixby/apistar/pull/1/files

My intentions are to simplify the commands interface by allowing namespacing. Users can create groups of commands that can be nested within each other. Very similar to the way `Include` works with routes.

Previously, all the backend commands were prefixed with their respective library names. `apistar django_makemigrations`, `apistar django_migrate`, etc... Using subcommands, we are able to join these together into `apistar django --help`, `apistar django makemigrations`, `apistar django migrate`. 

This is building off of the 0.2.0 version branch.
```python
django_commands = SubCommand(
    'django',
    [
        Command('makemigrations', make_migrations),
        Command('migrate', migrate),
    ],
)

app = App(commands=[django_commands, Command('other', other), ... ])
```

The current output in the MVP is not this clean, but potentially could look like:

```
bash-3.2$ apistar --help
Usage: apistar [OPTIONS] COMMAND [ARGS]...

  API Star

Options:
  --version  Display the `apistar` version number.
  --help     Show this message and exit.

Commands:
  django        Perform Django framework commands (makemigrations, migrate, etc)
  new            Create a new project in TARGET_DIR.
  run              Run the current app.
  schema      Output an API Schema.
  test           Run the test suite.
```
```
bash-3.2$ apistar django --help
Usage: apistar django [OPTIONS] COMMAND [ARGS]...

  Django Framework Commands. Perform various commands from the Django toolkit...

Options:
  --help     Show this message and exit.

Commands:
  makemigrations        Create new migrations files
  migrate            Execute the migrations
  run              Run the current app.
```

I also played around with adding `help` and `description` to the parsers by adding kwargs to the Command and SubCommand classes.

```python
commands = [
    Command('makemigrations', make_migrations, help='Perform migrations', description='Perform migrations')
]
```

**Comment by jwbixby** [comment]
Also, not sure where I can best report this. I am unable to verify my email on `discuss.apistar.org`. I receive the message below after clicking "Click here to activate your account".

```
[
"BAD CSRF"
]
```

**Comment by tomchristie** [comment]
>  I receive the message below after clicking "Click here to activate your account".

Can you double check that against https://discuss.apistar.org/ now, and let me know if you get the same issue? Bit of a problem if so.

Interesting suggestion, yes. I'll have more bandwidth to think this through once 0.2 is *actually* released, but I think there may be some milage in this.

First thing would likely be a pull request that updated the docs, and the `CommandConfig` interfaces, but *didn't* implement the behavior in the component to start with. That level of pull request would allow us to review and okay the design first.

> I also played around with adding help and description to the parsers by adding kwargs to the Command and SubCommand classes.

Yup, also interesting. We'll need to let things settle down there first as I need to think about the different ways we might want to specify these bits of information, and ensure that they play nicely with both the command line, and the api docs.

**Comment by jwbixby** [comment]
Thanks for the reply! 

> First thing would likely be a pull request...

I can get a PR out for the docs and interfaces to get some feedback on the idea and design. 

> Can you double check that against https://discuss.apistar.org/ now, and let me know if you get the same issue? Bit of a problem if so.

Its still happening on the verification emails that I originally received. When I attempt to log in now, I receive "Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?".

**Comment by tomchristie** [comment]
> I can get a PR out for the docs and interfaces to get some feedback on the idea and design.

Great.

> Its still happening on the verification emails that I originally received. When I attempt to log in now, I receive "Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?".

😕  I think there's some problem here around the http vs the https discourse site. Not totally clear.

**Comment by tomchristie** [comment]
> I am unable to verify my email on discuss.apistar.org. I receive the message below after clicking "Click here to activate your account".

That should be fixed now.

And yup, I think this issue is definitely going to be worth addressing, particularly wrt. database backends or migrations, that can have a lot of associated commands.

**Comment by tomchristie** [comment]
Given that we don't have command line routing back in yet we may as well close this off for now.
