### ISSUE TITLE
http.Request component listed in README.md but removed in 0.2

### ISSUE THREAD

**Issue by androiddrew** [encode/apistar#239]
Woke up to find 0.2 this morning and immediately upgraded. Noticed that you are still listing in the README.md that the http.Request component is still part of the framework but I see it was removed from that module. 

So how do I interact with the Request now if that component was removed?

**Comment by tomchristie** [comment]
That's an oversight yup. Will address that and a few other bits in a 0.2.1 tomorrow or Friday. Thanks for bringing it to my attention.

**Comment by androiddrew** [comment]
No worries. Took me a while to figure out you moved the component initialization to apistar.frameworks.wsgi.py. Got my API backup and running now. Looking great like what you did with the refactoring.

**Comment by tomchristie** [comment]
Yeah. Plenty shuffling around to do as things progress no doubt, but the fundamentals feel nailed down to the floor now.
