### ISSUE TITLE
comparison to hug?

### ISSUE THREAD

**Issue by AlJohri** [encode/apistar#242]
hi @tomchristie, would love to see a comparison of apistar to hug. some of the ideas behind both frameworks seem similar: https://github.com/timothycrosley/hug where hug seems like a bit more flask esque

**Comment by ssteinerx** [comment]
I've been/have used both.  Do you have a specific use case in mind?

**Comment by tomchristie** [comment]
Probably worth taking this to the discussion group https://discuss.apistar.org as it's a general discussion topic rather than a resolvable issue.

**Comment by AlJohri** [comment]
Ah, thanks. Will do.

**Comment by tomchristie** [comment]
👍
