### ISSUE TITLE
flatten_routes() is order-sensitive and gets the wrong path when Include precedes Route

### ISSUE THREAD

**Issue by jlowin** [encode/apistar#247]
When a list of routes that contains an `Includes` object before a `Route` object is passed to `apistar.core.flatten_routes`, the path of the Includes object is assigned to the Route object. For example:

```python
import apistar
from apistar import Include, Route

routes = [
    Include('/nested', [Route('/a', 'GET', lambda: 'a', name='a')]),
    Route('/x', 'GET', lambda: 'x', name='x'),
]

flat_routes = apistar.core.flatten_routes(routes)
assert flat_routes[0].path == '/nested/a'

# This check fails; the path picked up the parent route of the preceding Include
assert flat_routes[1].path == '/x' 
```

The cause of the bug is an inplace assignment to `prefix_path` in the `Include` branch of `flatten_routes()` [here](https://github.com/encode/apistar/blame/master/apistar/core.py#L75); `prefix_path` is then reused by any subsequent `Route` objects.

**Comment by jlowin** [comment]
In fact, it also affects any `Includes` objects that are come later in the list:
```python
routes.append(Include('/nested_again', [Route('/b', 'GET', lambda: 'b', name='b')]))
# Assert fails because the path becomes '/nested/nested2/b'
assert apistar.core.flatten_routes(routes)[2].path == '/nested2/b' 

```

**Comment by tomchristie** [comment]
Yup, looks valid on a quick skim. Tweaking the tests so that they catch this error and resolving the erroneous assignment both needed. Pull requests would be most welcome, but I'll resolve it in otherwise. Thanks so much for raising this!

**Comment by jlowin** [comment]
Just pushed! Let me know if it looks ok.

**Comment by shomodj** [comment]
Shouldn't this be a new release? upgrading to 0.2.1 broke my urls, using this revision it fixed it.

**Comment by tomchristie** [comment]
Yeah, incoming shortly.
