### ISSUE TITLE
Schema generation is wrong for custom models

### ISSUE THREAD

**Issue by Birne94** [encode/apistar#253]
Defining a custom user object and using it within a route:

```python
class User(Object):
    properties = {
        'name': String,
        'age': Integer
    }

def welcome(user: User):
    if user is None:
        return {'message': 'Welcome to API Star!'}
    return {'message': 'Welcome to API Star, %s!' % user['name']}
```

Will result in a wrong schema documentation:

```json
"fields":[  
    {  
        "name": "user",
        "required": true,
        "location": "body",
        "schema": {  
            "_type": "string",
            "title": "",
            "description": ""
        }
    }
]
```

User obviously is not a string.

Digging a little bit through the code this is caused by the handling in `apistar.components.schema.get_param_schema` which does not account for custom models. coreschema provides a `coreschema.Object` class which could be used here if `annotated_type` is a subclass of `apistar.typesystem.Object`.

Adding support for this recognised the model as an object, but failed to expand it further.

```python
def get_param_schema(annotated_type: typing.Type) -> coreschema.schemas.Schema:
    ...
    elif issubclass(annotated_type, typesystem.Object):
        return coreschema.Object(properties=annotated_type.properties)
    ...
```

Result:

```js
"fields": [  
    {  
        "name": "user",
        "required": true,
        "location": "body",
        "schema": {  
            "_type": "object",
            "title": "",
            "description": ""
        }
    }
]
```

**Comment by tomchristie** [comment]
Yup, the schema generation is provisional.
At the moment we're not properly pulling through the details on composite types.

**Comment by tomchristie** [comment]
#400 Handles the schema generation really nicely using OpenAPI, and no longer just naively treats everything as strings. Shaping up for a release fairly soon.
