### ISSUE TITLE
using django-admin cli commands?

### ISSUE THREAD

**Issue by AlJohri** [encode/apistar#260]
I think this is pretty related to https://discuss.apistar.org/t/custom-django-settings-and-manage-py-commands/187

I have a bunch of management commands I've written for creating, dropping, and refreshing databases that I use with my django apps. I was expecting to just set the `DJANGO_SETTINGS_MODULE` to something and continue using the `django-admin` cli. Would this be in scope? Is there another way to do this sort of like the sqlalchemy backend's cli with `create_tables`?

**Comment by tomchristie** [comment]
I think eventually we'll probably want to have versions of API Star where you plug the application into Django's URLs and just get API star style handlers running under the complete Django stack. The "just run the Django ORM" thing we have going at the moment isn't really a very complete solution.
