### ISSUE TITLE
subdomain on routes

### ISSUE THREAD

**Issue by ddorian** [encode/apistar#261]
Is it possible to specify a subdomain on rotues ? 
So they would match only on `abc` subdomain ? 
What about `<dynamic>` subdomain ? (maybe best in a component)

**Comment by tomchristie** [comment]
Currently no - the interface to `Router.lookup` doesn't provide for that... https://github.com/encode/apistar/blob/master/apistar/interfaces.py#L18

A workaround for now could be to have a wsgi app that routes to either app A or app B depending on the subdomain. Yes it's probably something we'll want to address at some point.

**Comment by tomchristie** [comment]
This is a long way off from being a priority for us, so I'm going to close it off as inactive.
