### ISSUE TITLE
Maybe want a way to run async init methods on components

### ISSUE THREAD

**Issue by anentropic** [encode/apistar#263]
As discussed here:  
https://discuss.apistar.org/t/how-to-inject-db-connection-in-async-mode/190/5

Currently `AsyncDependencyInjector.run_async` method only gets called when processing an async view method. Component preloading also uses the dependency injector, but the non-async `run` method is called instead.

This means it's not currently possible to make a Component with an async `init` method, which may be a useful thing to have.

**Comment by tomchristie** [comment]
Let's track this against #413.
