### ISSUE TITLE
The generated documentation is wrong

### ISSUE THREAD

**Issue by kianxineki** [encode/apistar#269]
```python
from modules.auth import UserModel as User


def welcome(user: User, name):
    return {'hello': user.username}

routes = [
# ...
    Route('/example/{name}', 'GET', welcome),
# ...
]
```
http://localhost:5000/docs/ show the user for query parameters! 🤕 
![dude](https://user-images.githubusercontent.com/3725538/29951994-b9c93e14-8ec6-11e7-9ff4-68df3e199377.jpg)

**Comment by tomchristie** [comment]
Can you include 'UserModel' in the example? It not clear what your doing exactly otherwise.

**Comment by kianxineki** [comment]
@tomchristie my code: https://github.com/kianxineki/apistar_boilerplate

UserModel is irrelevant (not sure :dancer: ), I update first post.

views: https://github.com/kianxineki/apistar_boilerplate/blob/master/exampleapp/views/example.py
urls: https://github.com/kianxineki/apistar_boilerplate/blob/master/exampleapp/urls/example.py
app: https://github.com/kianxineki/apistar_boilerplate/blob/master/exampleapp/app.py

**Comment by tomchristie** [comment]
Closed via https://github.com/encode/apistar/commit/4aee8b4bde3a23be1dd0c9089c286d6484d54d48

**Comment by kianxineki** [comment]
@tomchristie thx! fast fix!
