### ISSUE TITLE
Parameter not retrieved from request body in POST?

### ISSUE THREAD

**Issue by mjmare** [encode/apistar#273]
The docs say: 

> Parameters which do not correspond to a URL path parameter will be treated as query parameters for GET and DELETE requests, or part of the request body for POST, PUT, and PATCH requests.

which let me to expect that POSTing to this handler 

```
def search_docs(term: typesystem.String):
    print('term ', term)
    # do stuff
    return result
```
with a json body of {'term': 'blabla'} would fill the 'term' parameter from the body with the value 'bla', instead of None. 

Tested in ApiStar 0.2.10.
Route is: Route('/api/search', 'POST', search_docs),

If OTOH I use: 
```
def search_docs(data: RequestData):
    print('term ', data['term'])
    # do stuff
    return result
```
it works fine

**Comment by tomchristie** [comment]
Those docs were out of date and have just recently been updated.

Scalars (int, str, etc...) default to query parameters. List and Dict types default to the request body.
One feature on the to-do list is ensuring that you can control the locations if you need to change from the default behavior.

**Comment by mjmare** [comment]
Thx Tom.
Based on the current docs "Parameters which do not correspond to a URL path parameter will be treated as query parameters for scalar types such as int or str, or part of the request body for composite types of dict and list." it is not clear (to me) what to do if I want to extract a parameter from the body automatically. 
Given a body: {"term": "blabla"} What should be the function signature to extract the parameter "term"?
Neither 
```def search_docs(term: typesystem.String):```
nor
```def search_docs(term):```
work.

**Comment by pikeas** [comment]
@tomchristie Same question as @mjmare here!

**Comment by randvis** [comment]
@mjmare, I don't think there's a way to extract post data into function parameters. As you mentioned, the following way works, right? You get post data inside view function.
```
def search_docs(data: RequestData):
    print('term ', data['term'])
    # do stuff
    return result
```

**Comment by mjmare** [comment]
@randvis Correct.
