### ISSUE TITLE
how to document the response structure?

### ISSUE THREAD

**Issue by kianxineki** [encode/apistar#275]
```python
from apistar import typesystem
import typing


class User(typesystem.Object):
    properties = {'name': typesystem.string()}


def example() -> typing.List[User]:
    return [User({'name': str(x)}) for x in range(10)]
````

in the self-generated documentation there is no example of the structure, any ideas?

**Comment by tomchristie** [comment]
Planning to address that at some point yes. Just not there yet.

**Comment by antoine-de** [comment]
I think that would be a really nice feature and I'm willing to lend a hand on this, but I'm a bit lost, I think I can manage the api star part (hopefully) but, it seems to have to be implemented in core api too, but don't really know how it fits into the [Link model](https://github.com/core-api/python-client/blob/master/coreapi/document.py#L186).

Is it already implemented in coreapi ?

**Comment by frol** [comment]
@tomchristie Is this tracked somewhere else or why is this closed?
