### ISSUE TITLE
Generated documentation mangles formatting in docstrings

### ISSUE THREAD

**Issue by ojacobson** [encode/apistar#288]
Given

```python
def some_service():
  """Perform a service.

  This docstring has two logical paragraphs."""
  return "Hello!"
```

the generated documentation using `apistar.handlers.docs_urls` presents as

> Perform a service. This docstring has two logical paragraphs.

with a single visual paragraph.

While I'm not sure whether API Star should assume reST, Markdown, or something else, the inability to use something as fundamental as paragraphs in the published API documentation is pretty painful.

**Comment by tomchristie** [comment]
We'll make it configurable in due course yup. Quite likely that Markdown will be default formatting choice.

**Comment by tomchristie** [comment]
Well "the docs have currently been removed as part of a major reworking for 0.4" isn't a great answer, but that's where we are. We'll come back to them in due course.
