### ISSUE TITLE
Lifecycle of sqlalchemy_backend.Session is surprising

### ISSUE THREAD

**Issue by ojacobson** [encode/apistar#289]
Given

```python
class SomeRepository(object):
  def __init__(self, session):
    self.session = session
  # component methods omitted

def inject_repository(session: Session):
  return SomeRepository(session)

components = [
  Component(SomeRepository, inject_repository),
]
```

then when injecting a `SomeRepository` as follows:

```python
def use_a_repository(repo: SomeRepository):
  pass
```

will cause the following operations to occur, in order, during a request:

1. The `Session` provider begins a transaction.
2. The `Session` provider yields a session object.
3. API Star passes the session to `inject_repository` and captures the return value.
4. The `Session` provider commits and closes the session object.
5. API Star calls `use_a_repository` with the result from calling `inject_repository`.

The fact that the session was already closed by the time the request method starts caught me completely by surprise. I suspect this affects any component that returns a `typesystem.Generator`, and it doesn't look easy to address.

**Comment by ojacobson** [comment]
This turned out to be pilot error: I didn't have `preload = False` in the Component initializer. This could probably use some elaboration in the docs, but with that option, the above configuration became unsurprising.

**Comment by tomchristie** [comment]
Gotcha. I'm not entirely happy with the API for installing components yet, so sure there's more we could do here.
