### ISSUE TITLE
Should apistar have typesystem.Email

### ISSUE THREAD

**Issue by rougeth** [encode/apistar#293]
I'm using apistar for a new work project (I hope I can contribute more to the project now :) and I was doing a login view where the user enter its email. There is nothing to validate it, right? Should we have it? If you, I'd be happy to do it. We could have something like Django email validator (https://github.com/django/django/blob/master/django/core/validators.py).

**Comment by tomchristie** [comment]
We'll want to have something like 'input_type=...' on string, which we'll use to support email, URL, datetime and other validation yup.

**Comment by rougeth** [comment]
I believe `validators` would be a better name. The API reference describe the `format` attribute, do you imagine that `email` would be an option too?

**Comment by tomchristie** [comment]
'format' is best yes, losing track of myself there. We'll have 'validators' as a separate thing too in due course (format will be a constrained subset that impact eg form rendering, and schema descriptions, validators will be anything else eg. Check uniqueness against database)

**Comment by rougeth** [comment]
Nice @tomchristie, thanks!
