### ISSUE TITLE
Test cli arguments

### ISSUE THREAD

**Issue by rougeth** [encode/apistar#294]
To run `pytest`  over the project layout below, it would be needed the argument `--pyargs project`. Since `apistar test` run pytest, would be great to pass its args/kwargs e.g. `apistar test --pyargs project`
```
project/
    __init__.py
    app.py
    view.py
    test/
        __init__.py
        test_app.py
        test_view.py
        ...
```

More on: https://docs.pytest.org/en/latest/goodpractices.html#test-discovery

EDIT:
Obviously you have a lot of thoughts on this. Since the project I'm working on right now is using apistar,  I saw a great opportunity to help the project.

**Comment by tomchristie** [comment]
Dropping apistar from running py.test as of #400. Better to just have it completely decoupled from the test runner.
