### ISSUE TITLE
Document how to use dependency injection in tests

### ISSUE THREAD

**Issue by roncohen** [encode/apistar#307]
My views often take `session: Session` and `auth: Auth` parameters. I can use the TestClient to test them, but my initial reaction when trying to test my views was to try and get the dependency injection mechanism working on those views. I haven't been able to figure out how, so it would be great with an example in the docs.

**Comment by imanhodjaev** [comment]
Would be very nice to have more documentation on testing.

**Comment by JulienPalard** [comment]
I use `monkeypatch` on `app.http_injector.components` to patch my components:

```
from app import app
from apistar import TestClient
from my_server.my_components import Session, Auth

def test_hello_world(monkeypatch):
    monkeypatch.setitem(app.http_injector.components, Session, lambda: None)
    monkeypatch.setitem(app.http_injector.components, Auth, lambda: None)
    client = TestClient(app)
    response = client.get('/hello_world/')
    assert response.status_code == 200
    assert response.json() == {"hello": "world"}
```

You now just have to replace `lambda: None` by any mock or whatever.

If you want to do it for every requests, using a fixture may help:

```
@pytest.fixture
def client(monkeypatch):
    """Builds a test client, to simulate HTTP requests on it.
    Also patch the client components to avoid hitting the database.
    """
    monkeypatch.setitem(app.http_injector.components, Session, lambda: None)
    monkeypatch.setitem(app.http_injector.components, Auth, lambda: None)
    return TestClient(app)


def test_hello_world(client):
    response = client.get('/hello_world/')
    assert response.status_code == 200
    assert response.json() == {"hello": "world"}

```

**Comment by tomchristie** [comment]
General answer is going to be "don't". Either use the test client, or provide parameters explicitly.
We *could* document using the dependency injection independently of other parts of the system, which would be pretty reasonable, tho not a big priority at the moment.
