### ISSUE TITLE
Empty payload don't raise validation exception

### ISSUE THREAD

**Issue by rougeth** [encode/apistar#310]
```python
class Product(typesystem.Object):
    properties = {
        'name': typesystem.string(max_length=100),
        'rating': Rating,
        'in_stock': typesystem.Boolean,
        'size': ProductSize,
    }

def create_product(product: Product):
    ...
```

Considering the example above:

1. If I send a request with the wrong payload (`{}` or `[]` or `{key': 'value'}`) to `create_product`, it returns an error saying that the request is missing required params;

2. If I send a request with an empty payload, no error is raised and the `product` variable is equal do `None` in the view.

At the second point, shouldn't it raise an error too?

**Comment by tomchristie** [comment]
Yup, it should.

**Comment by tomchristie** [comment]
Verified that empty payloads do now result in 400 responses, as of the latest release.
