### ISSUE TITLE
Redirect responses with entities are not rendered

### ISSUE THREAD

**Issue by ojacobson** [encode/apistar#317]
Skipping rendering for redirect replies (added in 9c15dc3) causes redirects that include a body to fail unless that body is a `bytes`. For example,

```python
    return Response(
        Submission(download_url=download_url),
        status=HTTPStatus.SEE_OTHER,
        headers={
            'Location': download_url,
        },
    )
```

causes

```
[2017-10-09 13:02:30 -0400] [1366] [ERROR] Error handling request
Traceback (most recent call last):
  File "/Users/owen/Development/grimoire.ca/cadastre/.venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 182, in handle_request
    resp.write(item)
  File "/Users/owen/Development/grimoire.ca/cadastre/.venv/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 343, in write
    raise TypeError('%r is not a byte' % arg)
TypeError: 'download_url' is not a byte
```

way down the line. These responses are unusual, but are RFC-legal:

> Except for responses to a HEAD request, the representation of a 303 response ought to contain a short hypertext note with a hyperlink to the same URI reference provided in the Location header field.

**Comment by tomchristie** [comment]
Okay, that's legit, thanks.

**Comment by tomchristie** [comment]
Just confirmed to myself that's no longer the case in 0.4, 0.5.

**Comment by ojacobson** [comment]
Thanks! I'll have a look at this when I upgrade my own apps.
