### ISSUE TITLE
Curated list of 3rd party components

### ISSUE THREAD

**Issue by maziarz** [encode/apistar#318]
Would it make sense to have a list of 3rd party components in a section on the docs? I am starting to miss this type of information.

**Comment by mammuth** [comment]
Something like "Common 3rd party packages" definitely makes sense I think :+1:
So as of now there are:
- Alembic migrations
- JWT Auth Component
- ?

**Comment by maziarz** [comment]
I have pushed the section to the README.md.. @tomchristie can adjust it so it fits to his style :-)

**Comment by maziarz** [comment]
https://github.com/encode/apistar/pull/321

**Comment by maziarz** [comment]
https://github.com/encode/apistar/pull/321
