### ISSUE TITLE
No response and blocking request running in production

### ISSUE THREAD

**Issue by wq7** [encode/apistar#322]
Hello！
I found a problem in a production environment.
After the interface is thrown exception, the client will not receive any response, and the subsequent requests are blocked.
Using the command `apistar run`, a will pass DebugMiddleware, middleware handle exceptions and return 500 response.
But,
I'm using the command `uvicorn app:app --workers=4 --bind=0.0.0.0:80 --pid=pid`, in this case, you skip the processing of the middleware directly, resulting in the above problem.
I use the command `apistar run --no-debug` locally, too. Is middleware processing necessary?

My solution now is to rewrite the `ASyncIOApp`, do not raise exception in method `exception_handler`, but return 500 response. Is there a problem with the way I use `ASyncIOApp`?

(Insert a digression, The command `apistar run` on the README `--no-debugger` is incorrect. It should be `--no-debug`)

**Comment by tomchristie** [comment]
Given that both Uvicorn https://github.com/encode/uvicorn/pull/63 and API Star #400 are getting complete overhauls I think we should close this off. We can look into any blocked requests/responses if we still have issues with API Star 0.4 and Uvicorn ASGI
