### ISSUE TITLE
Zappa static files and interactive docs

### ISSUE THREAD

**Issue by olirice** [encode/apistar#324]
When deploying an API Star app using Zappa all endpoints the "stage" from zappa_settings.py is inserted as a prefix on all urls. 

for example
```python
# app.py
def welcome(name):
    return {'message': f'Welcome to API Star, {name}'}

routes = [Route('/hello', 'GET', welcome)]

app = App(routes=routes)

if __name__ == '__main__':
    app.main()
```

```json
# zappa_settings.json
{
    "dev": {
        "app_function": ...
        ....
    }
}
```

Will cause the route defined internally as "http://domain/hello?name=oliver" to be accessible at "http://domain/dev/hello?name=oliver".

That change breaks all route references that are generated dynamically in the application like static files and the schema docs.

I'm not familiar with the jargon around web apps so if that doesn't make sense, in short, the interactive docs break when deploying with Zappa.

One possible solution:
From the Zappa docs, 

>  If your project needs to be aware of the type of environment you're deployed to, you'll also be able to get `SERVERTYPE` (AWS Lambda), `FRAMEWORK` (Zappa), `PROJECT` (your project name) and `STAGE` (dev, production, etc.) variables at any time.

So it feels like the following snippet could solve the problem:
```python
import os
framework = os.environ.get('FRAMEWORK')
stage = os.environ.get('STAGE')

if framework == 'Zappa' and stage:
    # prepend `stage` to all routes
```

So far I haven't been able to locate the magical place where that snippet needs to live. I'm happy to submit a PR to update the routes and/or README if someone could point me in the right direction.

**Comment by jonatasbaldin** [comment]
I'm having this issue too, anyone knows how could we fix it?

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
