### ISSUE TITLE
Where people can make improvement suggestions like PEP or RFC

### ISSUE THREAD

**Issue by imanhodjaev** [encode/apistar#327]
Hi all,

I wonder if there is more specific repository or place except discuss forum? Where people can make suggestions on implementation of features and improvement of existing so @tomchristie and other contributors can review them.

Thanks.

**Comment by tomchristie** [comment]
I'm not sure what you mean. Either use pull requests / issues here for concrete problems, or https://discuss.apistar.org/ for open-ended threads.

**Comment by imanhodjaev** [comment]
@tomchristie thanks for clarification.
