### ISSUE TITLE
use of multiple databases

### ISSUE THREAD

**Issue by sdementen** [encode/apistar#329]
is it possible to define different databases via SQLAlchemy and be able to get the Session for the requested DB ? something like
```python
from apistar.backends.sqlalchemy_backend import Session

SessionDB1 = Session(NAMEOFDATABASE1)
SessionDB2 = Session(NAMEOFDATABASE2)

def create_customer(session: SessionDB1, name: str):
    customer = Customer(name=name)
    session.add(customer)
    session.flush()  # Flush the changes to the database. This will populate the customer id.
    return {'id': customer.id, 'name': customer.name}
```
with a configuration like
```python
settings = {
    "DATABASES": {
    "default": {
        "URL": "postgresql://:@localhost/apistar",
        "METADATA": Base.metadata
    },
    "DB1": {
        "URL": "postgresql://:@localhost/apistar1",
        "METADATA": Base.metadata
    }
}
}
```

**Comment by androiddrew** [comment]
So you have some routes that use one database and another route that uses a different one. What is the use case for this behavior? 

Your `SessionDB1` and `SessionDB2` are not registered components and will not be injected by the `DependencyInjector` in this case.  With your settings in that structure you will need to create two separate Components that return the appropriately configured Session objects and register those with your app.  You can use the README.md and the `apistar.backends.sqlalchemy_backend` module to see how the framework supplied Session Component is defined and copy that in your code.

If that satisfies your query consider closing this issue.

**Comment by seanhead** [comment]
I could see wanting to have segmentation based on use case for tuning reasons.  I'm going to be hitting this same kind of issue soon with postgres for most things, but postGIS for specific things.

**Comment by sdementen** [comment]
I build an API that needs both a DB for the internal needs of the API + a DB from a legacy system. For some endpoints, both are needed.

**Comment by tomchristie** [comment]
Defo a valid use case, yup. I’d suggest that alongside #400 we might want to include an example demonstrating how you can use components parameterized by the argument name in order to achieve this.

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
