### ISSUE TITLE
Attaching listener to the event loop

### ISSUE THREAD

**Issue by barrachri** [encode/apistar#338]
I'd like to use apistar in a microservices stack.

The idea is to have apistar serving some http APIs but also listen on RabbitMQ's queues.

You can easily do this with aiohttp for [example](http://aiohttp.readthedocs.io/en/stable/web.html#background-tasks).

Basically you need to have access to the asyncio loop:

```python
app['redis_listener'] = app.loop.create_task(listen_to_redis(app))
```

Is possible with apistar to do something similar? Can you access the loop through the app instance?

**Comment by tomchristie** [comment]
Use `asyncio.get_event_loop()`
