### ISSUE TITLE
Misspelling in exception

### ISSUE THREAD

**Issue by vulnersCom** [encode/apistar#340]
apistar.exceptions.ConfigurationError: Route **wtih** name "welcome" exists more than once. Use an explicit name="..." on the Route to avoid a conflict.

apistar/components/router.py, line 27, in __init__

**Comment by pavelholvi** [comment]
PR here: https://github.com/encode/apistar/pull/348

**Comment by tomchristie** [comment]
Obsoleted by the upcoming #400. Thanks!
