### ISSUE TITLE
Allow app.py to be in a package

### ISSUE THREAD

**Issue by JulienPalard** [encode/apistar#341]
I'd prefer to have app.py as a module in a package than to have it at the root. It would also allow for its name to be changed (and the package to be installed by `setup.py`).

Maybe I missed something but installing "app.py" from a setup.py would conflict between apistar projects or is there a way to "alias" a module from setup.py at install time? I almost never install modules, only packages.

Having app.py as a module fixes some issues:

- It allows the package to be installed
- It allows the installed package to be easily imported from tests
- And to be imported by linters (which may be started by a path different than the root)
- It allows the file to be renamed
- It allows one to specify which project to start as an apistar argument, like apistar run mypackage.app (fixes https://github.com/encode/apistar/issues/258)

I tried it by moving my `app.py` to my package, and now my app.py at the root contains only `from mypackage.app import app`.

From my tests I can now import `from mypackage.app import app` instead of `import app`.

Now `pytest` works (yes apistar tests already worked and still work), and my editor stopped complaining about app not being in the path (yup it starts `pylint test_app.py` not `pylint tests/test_app.py`).

It looks like it can be done without breaking the current behavior, but we may reintroduce an `apistar new --layout something` to allow one to have a simple "two files and it works", and allowing others to build a full hierarchy with packages, tests, setup.py, and a one-line, optional, app.py maybe containing something like "this file can be safely removed if you're willing to pass the package name each time you run apistar".

**Comment by androiddrew** [comment]
Instead of trying to bake a more complex template into the project scaffolding of the apistar executable have you looked at using cookiecutter? I do the same thing that you describe here and just scaffold all my projects off of a cookiecutter template.

**Comment by JulienPalard** [comment]
Make sense! I already use cookiecutter and love it, let's not re-invent working things, thanks for the enlightment.

**Comment by tomchristie** [comment]
Similar to #350. Actually I think we’re going to remove the cutesy usage of ‘apistar’ when you can just run app.py directly. Likely to be removed as part of the overhaul in #400
