### ISSUE TITLE
Mongo DB backend

### ISSUE THREAD

**Issue by humrochagf** [encode/apistar#343]
Hi, I am using Mongo DB at my project and started to develop a backend to add mongodb support to apistar #342 trough pymongo and integrating it directly with the type system without the need of a intermediate mapping between pymongo and apistar typesystem.

If there's anyone with any thoughts about that, would be cool to talk on how to improve it.

**Comment by tomchristie** [comment]
Let's punt open-ended discussions onto https://discuss.apistar.org

Also, the docs clearly need to do better at demonstrating how to create components. (That gets a nicer interface in 0.4) It's pretty likely that the next version will remove built-in support for ORMs in favor of a well-supported component interface, and third party apps for ORM support.
