### ISSUE TITLE
Treat URL Argument as components

### ISSUE THREAD

**Issue by JulienPalard** [encode/apistar#344]
In the current implementation, URL arguments looks a special case, passed directly to views.

They may be treated as components, allowing to explicly tell where they come:

    routes = [Route('/things/{thing_name}', 'GET', views.get_thing)]
    [...]
    def get_thing(thing_name: URLArgument):
        ...

And wrap them with intermediate components like:

    Thing = namedtuple('Thing', 'thing_name')

    def make_thing(thing_name: URLArgument) -> Thing:
        ...
        return Thing(thing_name)
    
    routes = [Route('/things/{thing_name}', 'GET', views.get_thing)]

    app = App(routes=routes,
              components=[Component(Thing, init=make_thing)])

    def get_thing(thing: Thing):
        ...

Currently it looks not possible to depend on an URIArgument in a Component, and not dropping the URL Argument to the view signature raise:

    E   apistar.exceptions.ConfigurationError: URL Argument "thing_name" missing from view "<function get_thing at 0x...>".

It would still be possible to ensure the "thing_name" URLArgument is properly eaten by the chain of dependencies to raise some of:

    E   apistar.exceptions.ConfigurationError: URL Argument "thing_name" not used by view nor any of its dependencies "<function get_thing at 0x...>".

**Comment by JulienPalard** [comment]
Does it look like a good idea? Should I try to implement it?

**Comment by tomchristie** [comment]
‘PathParams’ and ‘PathParam’ are components in #400
