### ISSUE TITLE
Running app from other than the working directory

### ISSUE THREAD

**Issue by uranusjr** [encode/apistar#350]
Something like

```bash
apistar run ./api
```

to run the APIStar instance inside that directory, so users don’t need to change directory first. It might be a good idea to allow an entry point other than `app.py` as well.

**Comment by pslacerda** [comment]
In my setup the web application is an one of the apps in the source tree like:

```
.
├── myapp
│   ├── gateway
│   │   ├── app.py
│   │   ├── auth.py
│   │   ├── components.py
│   │   ├── __init__.py
│   │   ├── routes.py
│   │   ├── schema.py
│   │   └── views.py
│   ├── __init__.py
│   ├── models.py
│   └── services
│       ├── accounts.py
│       └── __init__.py
├── requirements.txt
```

And  `myapp.gateway.app` imports `myapp.gateway.components`  so it's impossible to run with

    cd myapp/gateway
    apistar run

neither

    python3 myapp/gateway/app.py --host=0.0.0.0 --port=8080


An viable approach is to be able to specify the `App` object as in

    gunicorn myapp.gateway.object:app \
        --worker-class=meinheld.gmeinheld.MeinheldWorker. 

Like

    apistar run myapp.gateway.app:app


I really appreciate something like this.

**Comment by k-dominik** [comment]
See discussion going on in https://github.com/encode/apistar/pull/259

**Comment by tomchristie** [comment]
The ‘apistar’ style invocation is a bit unnecessary, so will be dropping it as part of the overhaul in #400. (Just run python app.py) We will reintroduce a cli in due course but not in the current state where it’s mostly a simple proxy onto whatever app.py is in the current directory.
