### ISSUE TITLE
Feature request: datetime.date and datetime.datetime query/form param parsing

### ISSUE THREAD

**Issue by ojacobson** [encode/apistar#353]
The following doesn't work, but likely should:

```python
import datetime
def some_endpoint(before: datetime.datetime):
  pass
```

Attempting to call this endpoint produces the following:

<details>

```
Traceback (most recent call last):
  File "/Users/owen/Development/grimoire.ca/cadastre/.venv/lib/python3.6/site-packages/apistar/components/dependency.py", line 114, in run_all
    func_steps = self._steps_cache[func]
KeyError: <function compute_state at 0x10baf0a60>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/owen/Development/grimoire.ca/cadastre/.venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/owen/Development/grimoire.ca/cadastre/.venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/owen/Development/grimoire.ca/cadastre/.venv/lib/python3.6/site-packages/apistar/frameworks/wsgi.py", line 134, in __call__
    response = self.http_injector.run_all(funcs, state=state)
  File "/Users/owen/Development/grimoire.ca/cadastre/.venv/lib/python3.6/site-packages/apistar/components/dependency.py", line 141, in run_all
    ret = step.func(**kwargs)
  File "/Users/owen/Development/grimoire.ca/cadastre/.venv/lib/python3.6/site-packages/apistar/frameworks/wsgi.py", line 130, in __call__
    response = self.http_injector.run_all(funcs, state=state)
  File "/Users/owen/Development/grimoire.ca/cadastre/.venv/lib/python3.6/site-packages/apistar/components/dependency.py", line 116, in run_all
    func_steps = self._create_steps(func)
  File "/Users/owen/Development/grimoire.ca/cadastre/.venv/lib/python3.6/site-packages/apistar/components/dependency.py", line 247, in _create_steps
    key, provider_func = self._resolve_parameter(param, func)
  File "/Users/owen/Development/grimoire.ca/cadastre/.venv/lib/python3.6/site-packages/apistar/components/dependency.py", line 208, in _resolve_parameter
    raise exceptions.CouldNotResolveDependency(msg)
apistar.exceptions.CouldNotResolveDependency: Injector could not resolve parameter before:datetime.datetime=None
```

</details>

It's not 100% clear what the right parsing behaviour here is; I'm partial to ISO8601 or to using [dateparser](https://dateparser.readthedocs.io/en/latest/), personally, but any pre-fab format would work.

Looking at the code and features, I _think_ this is independent of support for datetimes at the schema level.

Workaround:

```python
import datetime
def some_endpoint(before):
  before = datetime.datetime.strptime(before, SOME_FORMAT)
  ...
```

**Comment by funkybob** [comment]
If you have a parser function you trust, surely you can just register it as a component?

Component(datetime.datetime, init=my_datetime_parser),

**Comment by ojacobson** [comment]
Nope. The list of parameter conversions for query and form parameters is hard-coded in [dependency.py](https://github.com/encode/apistar/blob/master/apistar/components/dependency.py#L583-L589). A specific list of types are special and are handled separately from general dependency injection.

Registering an endpoint with a `datetime.datetime` parameter attempts to find a Component (or any other dependency) provider for that type, and then fails:

```
apistar.exceptions.CouldNotResolveDependency: Injector could not resolve parameter before:datetime.datetime
```

One can always add a Component, but it's not obvious how to access the name of the parameter from inside of a Component provider.

**Comment by funkybob** [comment]
A Type subclass?

**Comment by ojacobson** [comment]
I'm not sure I follow, and reviewing the code doesn't provide more insight. Can you expand on that?

**Comment by pikeas** [comment]
+1, also not sure how best to create a datetime component (or in our case, a component that turns a timestamp into a TZ-aware datetime).

**Comment by rhelms** [comment]
I'm hitting this issue now, when I realised the documented 'format' param for String doesn't seem to exist.

My take is to pick a base representation for your time (either `str`, `int` or `float`) for how you want it to appear in the API (I'll be selecting `str` for readability), and then extend a class from `str` that will parse a string representation of a `date` or `datetime`. and raise the appropriate TypeSystemError when things are not going as expected.

Given the complexities of dates and times, I'm not surprised this has been left as an exercise to the reader.

**Comment by jgirardet** [comment]
Hello,
I juste "fake subclass" String  and use a regex :

class FormattedDate(typesystem.String):
    """
    date formated yyyy-mm-dd
    """
    pattern = r"^([0-9]{4})(-)?(1[0-2]|0[1-9])(?(2)-)(3[0-1]|0[1-9]|[1-2][0-9])$"
    errors = typesystem.String.errors.copy()
    errors['pattern'] = "The following format should be used : yyyy-mm-dd"
    description = "Date formated yyyy-mm-dd

About your gist, un think using python-dateutil parser could replace your parse method

**Comment by tomchristie** [comment]
Yup 100% want to see this addressed. Planning to have it in for 0.4. #400
