### ISSUE TITLE
Components that always run?

### ISSUE THREAD

**Issue by pikeas** [encode/apistar#359]
I have some error handling middleware that should run on every request, to report unhandled errors to a bug tracking service. How can I bolt this onto Apistar?

**Comment by randvis** [comment]
I think you can write a `AFTER_REQUEST` hook `send_error_report`. The code might look like this:
```
settings = {
......
'AFTER_REQUEST': [send_error_report, render_response],
}
```

```
def send_error_report(handler: Handler,
                    injector: Injector,
                    settings: Settings,
                    exc: Exception,
                    ret: ReturnValue) -> http.Response:
    if isinstance(exc, exceptions.HTTPException):
       // send error report
    return ret
```

**Comment by skion** [comment]
Alternatively, I've sub-classed the WSGIApp and replaced its exception handler for this. 

```
def exception_handler(self, exc: Exception) -> http.Response:
```

Take care to use the exact signature including type annotation if you do this, or the `exc` parameter will have the value of `None`. This took me a while to figure out.

**Comment by randvis** [comment]
I think @skion's suggestion works fine, too.

Another thing just occurred to me is that to trigger exception handling, in view functions, you must raise Exceptions instead of calling something like:
`return Response(data, status=4xx/5xx, headers=headers)`.

**Comment by tomchristie** [comment]
Either of @skion or @randvis's suggestions. However in the big #400 we'll be getting much nicer event hooks.
