### ISSUE TITLE
The builtin StaticFiles component cannot handle static files change correctly

### ISSUE THREAD

**Issue by living42** [encode/apistar#360]
The builtin StaticFiles component is based on third party package called whitenoise, that package by default will cache some info of static files, for this case the Content-Length header. 

Because the cached Content-Length of static files, when you change some static file, especially the file's size is changed, request that changed file could cause some issues. If file size if bigger than cached Content-Length, the response will truncated, on the opposite the request will hang (browser waiting remaining bytes which is not exists). 

The whitenoise provide an option called `autorefresh` to change that behavior, but the `WhiteNoiseStaticFiles` cannot set this option. so maybe we should add this options to the `STATICS` inside of settings, or if there has some `DEBUG` option we can depend on is to set `autorefresh` automatically.

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
