### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by asyncee** [encode/apistar#363]
Hello, we are developing a new API by minimal viable product concept, that may be used later in production, and i'm interested in trying apistar for this purpose.

So the question is: will this project be maintained or actively developed by Tom or some "core" team? I have checked insights and noticed that there was 1 commit in repo for last month and zero closed issues.

P.S. i do understand that this project is not yet intended for production usage.

**Comment by audiolion** [comment]
@tomchristie was on vacation for much of October, he is spending Nov working on DRF according to their news release http://www.encode.io/reports/october-2017

its just taking a back seat for a bit.

I think you should probably use something else until this project hits 1.0

**Comment by asyncee** [comment]
Did not know about encode.io.

Thanks!
