### ISSUE TITLE
Use response status 307 instead of 302 for redirect handling

### ISSUE THREAD

**Issue by highfieldjames** [encode/apistar#365]
The [`Found` exception](https://github.com/encode/apistar/blob/973c6485d8297c1bcef35a42221ac5107dce25d5/apistar/exceptions.py#L63) currently has a `default_status_code` of `302`. Most browsers handle `302` responses by sending a `GET` request to the new `Location` despite the original method used.

I propose that the status code should be changed to `307 Temporary Redirect` which will honor the original HTTP method as recommended on the MDN web docs:

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307

I'd be happy to create a PR if approved.

Also, thanks for the great work with API Star so far! I've recently ported a small project from Django and it's been a delight! ⭐️

**Comment by tomchristie** [comment]
Okay, interesting.
Can we confirm if the python `requests` library honors that behavior?

**Comment by highfieldjames** [comment]
It is handled here by only stripping the request body from redirect requests that aren't either `temporary_redirect (307)` or `permanent_redirect (308)`:
https://github.com/requests/requests/blob/v2.18.4/requests/sessions.py#L167

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
