### ISSUE TITLE
Validation 200 OK with missing property

### ISSUE THREAD

**Issue by nek4life** [encode/apistar#369]
I have the following code.

    class Product(typesystem.Object):
        properties = {
            'name': typesystem.string(max_length=100)
        }

    def create_product(product: Product):
        return {'product': product}

    routes = [
        Route('/product/create', 'POST', create_product),
    ]

And I'm sending the following request

POST /product/create
Content-Type: application/json

    {
        "foo": "bar"
    }

And I get back the following response

    HTTP/1.0 200 OK
    content-type: application/json
    Connection: close
    Server: Werkzeug/0.12.2 Python/3.6.1
    Date: Sun, 03 Dec 2017 15:20:25 GMT

Shouldn't this request end up being a bad request because the request does not meet the specified properties in the Product type I've created?

API Star 0.3.9

**Comment by randvis** [comment]
You need to specify required fields. Try this.
```
class Product(typesystem.Object):
    properties = {
        'name': typesystem.string(max_length=100)
    }

    required = ['name']

```

**Comment by nek4life** [comment]
@randvis yup that worked, thanks! Just curious why there is a separate property specifically for required fields? It seemed more natural to me to specify whether the field was required or not on the actual property itself.

The documentation does not mention any of this in the validation section. I also had read somewhere in another comment that if a default wasn't specified the field was required which also seemed odd that it was explicitly set. At any rate I'll look into making a pull request to update the docs so they reflect the current way of making required fields.

**Comment by nek4life** [comment]
> Object
> 
> Validates dictionary or object input. A subclass of dict.
> 
>     default - A default to be used if a field using this typesystem is missing from a parent Object.
>     properties - A dictionary mapping string key names to typesystem or type values.
>     description - A description for online documentation
> 
> **Note that child properties are considered to be required if they do not have a default value.**

**Comment by kkinder** [comment]
Indeed, the documentation seems to suggest just the opposite of this: 

> Note that child properties are considered to be required if they do not have a default value.

Not so!

**Comment by tomchristie** [comment]
The type validation gets an overhaul in #400. Your example would be...

    from apistar import types, validators

    class Product(types.Type):
        name = validators.String(max_length=100)

There’ll be no need for ‘required’ on types anymore - a field is required if it doesn’t have a ‘default=‘ set on it.
