### ISSUE TITLE
typesystem.Integer default

### ISSUE THREAD

**Issue by trthhrtz** [encode/apistar#370]
```
class testVal (typesystem.Integer):
    minimum = 1
    maximum = 8
    default = 1
```
The default does not work

**Comment by randvis** [comment]
Can you give some code about how you use `testVal `?

**Comment by bahattincinic** [comment]
This is not a bug. Because `default` option only works with `typesystem.Object`

https://github.com/encode/apistar#number
**Documentation:**
```
A default to be used if a field using this typesystem is missing from a parent Object.
```
