### ISSUE TITLE
Sections in the sidebar

### ISSUE THREAD

**Issue by michaelhelmick** [encode/apistar#372]
I reached out to Tom on Twitter and he seemed keen to the idea, I thought it would be nice if there was a way to group routes in the sidebar.

Initial thought would be a keyword argument that gets passed to `Include`, maybe `section` or `group`. Although, we may be able to use the `namespace` keyword argument and maybe just display the section in the sidebar like this:

#### users_detail

Instead of how it currently is:

#### users:users_detail

I found with longer namespaces the sidebar text can become long and, for lack of a better term, not attractive in the UI.

**Comment by tomchristie** [comment]
We're going to have to reintroduce the API docs after 0.4 so we oughta close this off for now, and reassess once we've got them back in.
