### ISSUE TITLE
Support schema format in /docs/schema, similar to the command-line

### ISSUE THREAD

**Issue by anlutro** [encode/apistar#374]
It would be nice if we could `GET /docs/schema?format=openapi` for example.

**Comment by tomchristie** [comment]
Yup, possibly sometime. We're a bit of a way of from considering that an open thing to be worked on, so I'll close this off for now. Perhaps with a view to reopening once things are shaping up again. Also worth mentioning that as of #400 the default schema representation will be openapi.
