### ISSUE TITLE
Debug server not reloading with custom `run` command

### ISSUE THREAD

**Issue by pslacerda** [encode/apistar#375]
The reloader isn't trigged when some source file is edited if a custom command runs the development server.

```python
def command_run_develop(db: django_orm.Session,
                        host: str='127.0.0.1',
                        port: int=8080,
                        debug: bool=True,
                        reloader: bool=True) -> None:
    run_wsgi(app, host, port, debug, reloader)

app = App(commands=[Command('run_develop', run_develop)])
```

My guess is that this is related to `app: App` not to be injectable on custom commands. Can we inject `app: App` in such commands?

**Comment by tomchristie** [comment]
If we do re-introduce an `apistar run` at some point I think it's likely that we won't call into the codebase with python, but rather run it as a separate subprocess, and fully kill/restart the process on changes.

Closing in the meantime, since this isn't currently relevant.
