### ISSUE TITLE
Reverse relationship lookups through Schemas

### ISSUE THREAD

**Issue by audiolion** [encode/apistar#376]
Given the following:

```python

class Account():
    ...


class Transaction():
    account = models.ForeignKey(Account, related_name='transactions')

```

How do you have a serialization of Account return Transactions?

```python

class AccountSchema(typesystem.Object):
    properties = {
        'id': typesystem.integer(minimum=1),
        'transactions': typesystem.array(),
    }

```

Tried that but it didn't resolve the relationship, trying to get an array of primary keys

A separate issue but somewhat related to this, when doing a POST request for a new `Transaction` you need to (for Django at least) do a schema like:

```python

class TransactionSchema(typesystem.Object):
    properties = {
        'account_id': typesystem.integer(minimum=1),
    }

def create_transaction(request: http.Request, auth: Auth, session: Session, data: TransactionSchema):
    transaction = session.Transaction.objects.create(**data)
    return Response(TransactionSchema(transaction), status=201)
```

because if you just provide `account` django's ORM won't serialize the data properly. It would be nice to support `account` or `account_id` somehow.

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
