### ISSUE TITLE
Map Multiple HTTP Methods to same view function

### ISSUE THREAD

**Issue by audiolion** [encode/apistar#377]
```python
account_routes = [
    Route('/{uuid}/', 'PUT', views.update_account),
    Route('/{uuid}/', 'PATCH', views.update_account),
]
```

possible to have two methods like PUT/PATCH map to the same view function?

**Comment by mgaitan** [comment]
`Route` should accept a string or a tuple of string as methods 

```
account_routes = [
    Route('/{uuid}/', ('PUT', 'PATCH'), views.update_account),
]
```

**Comment by audiolion** [comment]
This should work but the way its coded it doesn't:

https://github.com/encode/apistar/blob/973c6485d8297c1bcef35a42221ac5107dce25d5/apistar/components/router.py#L40

it wraps what is passed in a list, so it would pass `[('PUT', 'PATCH')]` and then werkzeug fails to parse a tuple object when it calls:

```python
self.methods = set([x.upper() for x in methods])
```

**Comment by tomchristie** [comment]
Closing as per #386
