### ISSUE TITLE
apistar project still active?

### ISSUE THREAD

**Issue by pansen** [encode/apistar#382]
howdy, 

first of all, thanks for that great project; very intuitive and ambitiously work. currently i'm in the research phase for a python api framework for a bigger project. apistar would be my favourite. 

having that said, my impression is that this project kind of stalled. a couple of open, unanswered pull requests and issues. anybody here, who has insights about the motivation and development? are there others than @tomchristie who are maintainers?

i would be not only interested to use this framework, but also to contribute to the missing response types part. this of course would be another discussion, in case of active maintainers existent. 

best, andi

**Comment by rmk135** [comment]
> i would be not only interested to use this framework, but also to contribute to the missing response types part. this of course would be another discussion, in case of active maintainers existent.

+1

**Comment by 7robertodantas** [comment]
See this, it may answer your question. :smiley: 
https://discuss.apistar.org/t/what-happened-to-tom/324

**Comment by pansen** [comment]
aight. looks like activity :) thanks for your responses! @7robertodantas this is reassuring. 

in the meantime i was able to plug into the framework, registering a custom `apistar.core.Component`, which populates a custom `apistar.Schema` implementation. that is passing me a custom `apistar.Schema` with a new property up to the `Encoder`, which again needs some customization to publish my new field (that will be a response type then). 

the design looks awesome and really pluggable to me.

**Comment by audiolion** [comment]
The project is still in its alpha stages and there could still be large changes to the API. I would recommend that if this is for a production/work/enterprise related project to choose another framework for now. There are other api frameworks, [Falcon](https://falcon.readthedocs.io/en/stable/), [Django Rest Framework](django-rest-framework.org), [Flask-RESTful](https://flask-restful.readthedocs.io/en/latest/), or if you want async check out [Quart](https://gitlab.com/pgjones/quart) which converts flask's existing API to work with `async/await`

**Comment by pansen** [comment]
thanks for the warning @audiolion. 

i worked with DRF for more than 2 years and i know about its developer friendlyness. from that context i'm also aware of, what is possible with the leadership of tom. this experience and the obviously professional development style here, don't let me be scared. the only thing that i would be scared of is nobody beeing able to respond to PRs for weeks. 

another huge plus for apistar seems to be its performance, which is hard to gain e.g. with DRF. also fancy stuff like `async/await` based libs don't help too much i guess, if other requirement of a project will not be aware of this. 
e.g. imagine having the requirement for a payment api, like [Stripe](https://pypi.python.org/pypi/stripe/), which is python 2.x compatible, `async/await` is out. 

you think i'm too much positive? ;)

**Comment by pslacerda** [comment]
@audiolion yes, it isn't completly production ready but we are really pushing APIStar into production soon. We are using your apistar_jwt, took me some days to figure out the design reasoning of JWT but now I'm almost a fan.

@pansen there are many features lacking and we are implementing them as needed. But sometimes is hard to grasp and implement them, so I'm still waiting standard solutions for my problems.

I'm also concerned because the he stopped twitting and I'm missing the last december http://encode.io report.

**Comment by audiolion** [comment]
awesome to hear that you are using apistar_jwt, feedback always welcome on it!

Tom is just busy right now, he is working on private projects to earn money most likely as the grant funding has run out.

Perhaps he should set up a Patreon so the collective people can help out, but it seems like what he mostly tries to attain are sponsorships from companies.

**Comment by androiddrew** [comment]
A Patreon that pays out for every major/minor release? I'd throw down on that if it's possible.

**Comment by audiolion** [comment]
@androiddrew I would prefer to just do a monthly contrib, makes it easier for both supporters and patron to budget.

**Comment by androiddrew** [comment]
@audiolion I don't know much about how Patreon campaigns are run. I would agree that plenty of people would want to do that, but Tom's company has many projects. APIStar hasn't had a core update for many months, so I would effectively be funding other projects unrelated to APIStar. If I could payout a larger sum per release I would feel better that my money was going towards APIStar and not DRF.

**Comment by piotrek-py** [comment]
> i would be not only interested to use this framework, but also to contribute to the missing response types part. this of course would be another discussion, in case of active maintainers existent.

+1

**Comment by tomchristie** [comment]
Sorry, yeah I've been juggling a bit of freelance work too to keep the wheels spinning. @carltongibson's been getting funded time on REST framework and kickin' ass there. But yeah I *will* be coming back to API Star as soon as poss.

**Comment by tomchristie** [comment]
See #400.
