### ISSUE TITLE
Input for request body not showing in docs

### ISSUE THREAD

**Issue by fridex** [encode/apistar#391]
When I define an endpoint that serves POST, there is no input nor a documentation entry about accepting request data in the UI docs.

It would be nice to provide an input textarea for JSON inputs in the UI (once a user clicks on "Interact" button").

A simple reproducer:

```python
def foo(body: dict):
    return body

app = App(routes=[
    Route('/foo', 'POST', foo),
    Include('/docs', docs_urls),
    Include('/static', static_urls)
])
```

apistar version: 0.3.9

**Comment by bahattincinic** [comment]
You should define your data structure instead of `body: dict`

For example;

```python
from apistar import typesystem

class Product(typesystem.Object):
    properties = {
        'name': typesystem.string(max_length=100)
        'in_stock': typesystem.Boolean,
    }

def foo(body: Product):
    return body
```

If you want to get non-schema JSON data, you can use the following method.

```python
def foo(body: str):
    return JSON.loads(body)
```

**Comment by fridex** [comment]
@bahattincinic 

Thanks, that works!

On the other hand, there seems to be an error, when the `name` property is set to be of type `typesystem.Array`. The UI shows only input and any request results in 400 ``"name": "Must be a list."`` while parsing the submitted array.

**Comment by bahattincinic** [comment]
I think, the documentation doesn't support `typesystem.Array`. 

I tried to use Array Field in Documentation UI, the result was the same for me.

**Example Code:**

```python
from apistar import typesystem
from apistar import Include, Route
from apistar.frameworks.asyncio import ASyncIOApp as App
from apistar.handlers import docs_urls, static_urls


from apistar import typesystem


class Name(typesystem.Array):
    items = typesystem.String


class Product(typesystem.Object):
    properties = {
        'name': Name,
        'in_stock': typesystem.Boolean,
    }


def welcome(data: Product):
    return data


routes = [
    Route('/', 'POST', welcome),
    Include('/docs', docs_urls),
    Include('/static', static_urls)
]

app = App(routes=routes)


if __name__ == '__main__':
    app.main()
```

When I investigated this problem, I saw this problem also related to schema generation.

I didn't see ArrayField in the following output:
```
$ apistar schema
{"_type":"document","_meta":{"url":"/docs/schema/"},"welcome":{"_type":"link","url":"/","action":"POST","fields":[{"name":"name","location":"form","schema":{"_type":"string","title":"","description":""}},{"name":"in_stock","location":"form","schema":{"_type":"boolean","title":"","description":""}}]}}
```

I will try to fix it.

**Comment by bahattincinic** [comment]
@fridex  https://github.com/encode/apistar/pull/396 fixed.

**Comment by tomchristie** [comment]
Let's revisit this once we get the API docs back in following the big redesign of #400.
