### ISSUE TITLE
View anotated type not used in schema generation

### ISSUE THREAD

**Issue by leiserfg** [encode/apistar#395]
The generated schemas does not have response type, even when I am anoting it.

**Comment by Place1** [comment]
I believe this is a limitation of coreapi currently? Although support for this usecase is very close as I hear from the DRF mailing list.

**Comment by leiserfg** [comment]
openapi does suport  (and encurage) this

**Comment by tomchristie** [comment]
We'll be getting response schemas, yup. The 0.4 release uses openapi (v3) as the default schema representation, and we'll be addressing response schemas in #400.
