### ISSUE TITLE
typesystem.Integer causes error when optional description is added

### ISSUE THREAD

**Issue by EmanNo1** [encode/apistar#399]
When I add a description to an Integer field type there is an error. The same error occurs if default=0 is added.

File "location.py", line 5, in <module>
    class Location(typesystem.Object):
  File "location.py", line 22, in Location
    'external_id': typesystem.Integer(description='External Record ID from Database'),
  File "/home/erik/py_apps/2018/feb/apistar/.env/lib/python3.6/site-packages/apistar/typesystem.py", line 71, in __new__
    raise TypeSystemError(cls=cls, code='type') from None
apistar.exceptions.TypeSystemError: Must be a valid number.

**Comment by jgirardet** [comment]
with inline params, you should use lower case : typesystem.integer(description='External Record ID from Database')

**Comment by tomchristie** [comment]
The class style vs inline style is one of the things that I think is confusing and don't like about the existing types. Getting an overhaul and simplification in 0.4. (#400)
