### ISSUE TITLE
Uninjectable functions aren't called

### ISSUE THREAD

**Issue by pslacerda** [encode/apistar#422]
Functions that hadn't enough parameters to be injectable aren't called at all. I already saw this resulting in 404 which is the expected behaviour for views.

But when decoupling the dependency injection framework from the web part it should have an way to ensure that all `funcs` passed to `Injector.run()` had all dependencies injected.

```python
def func(unused: int):
    return 1

injector.run([func], {})
```

`unused: int` isn't resolved so func isn't called at al. This happens in 0.4. I suggest something like `ensure_all_run` kwarg parameter in `Injector.run()`.

**Comment by tomchristie** [comment]
I'm not able to replicate against the incoming 0.4 branch...

```python
from apistar.server.injector import Injector

def func(unused: int):
    return 1

injector = Injector(components=[], initial={})
injector.run([func], {})
```

Results in:

```bash
apistar.exceptions.ConfigurationError: No component able to handle parameter "unused" on function "func".
```

**Comment by pslacerda** [comment]
Sorry, I missed something.
