### ISSUE TITLE
No form encoding support in 0.4

### ISSUE THREAD

**Issue by Bogdanp** [encode/apistar#427]
It looks like [the only](https://github.com/encode/apistar/blob/3aed0e4b90c6c949b2a915b8e750658d87b0f7d5/apistar/server/validation.py#L16) codec that `RequestDataComponent` supports in 0.4 is `JSONCodec`. Are you planning to add support for form posts to `RequestData` later or are apps expected to roll their own `FormData` (or similar) component?

**Comment by tomchristie** [comment]
> Are you planning to add support for form posts to RequestData

Yup.

**Comment by tomchristie** [comment]
That’s a good easy one that ought to sit towards the top of our TODO pile.

**Comment by tomchristie** [comment]
I think we’d start with hardcoded json+form parsing, and treat configurable parsers/renderers as a later enhancement.

**Comment by Bogdanp** [comment]
Sounds good to me!

**Comment by tomchristie** [comment]
Closed via #430.
