### ISSUE TITLE
Singleton components

### ISSUE THREAD

**Issue by Bogdanp** [encode/apistar#431]
This is more of a question than anything, but it's based on an issue I ran into while porting a medium-sized (~1.5kloc) app from 0.3 to 0.4 last night. I found that the previous version of the app relied on singleton components/components instantiated with `preload=True` quite a bit and that usage seemed reasonable. In order to support the same pattern in 0.4, I ended up rolling my own generic `SingletonComponent`:

```python
from apistar import Component
from inspect import Parameter
from typing import Generic, Type, TypeVar

T = TypeVar("T")


class SingletonComponent(Component, Generic[T]):
    """A generic component that wraps singleton instances.
    """

    def __init__(self, instance: T, instance_type: Type[T] = None) -> None:
        self.instance = instance
        self.instance_type = instance_type or type(instance)

    def can_handle_parameter(self, parameter: Parameter) -> bool:
        return parameter.annotation is self.instance_type or \
            issubclass(parameter.annotation, self.instance_type)

    def resolve(self) -> Type[T]:
        return self.instance
```

I'm wondering if

1) there's another/builtin way of doing something like this that I'm just not seeing and,
2) if not, whether or not this class or something similar to it could be included in core.

Thanks!

**Comment by tomchristie** [comment]
I'll close this off as I think this is something more for general discussion at this point, rather than an open issue. I guess one question might be "why treat singletons as injected parameters?" (Eg. why not just instantiate a single instance and import and use that anywhere it's required)

We could take this to https://discuss.apistar.org/ if that's helpful.

**Comment by skion** [comment]
Opened a [thread](https://discuss.apistar.org/t/singleton-components/523) on the board...
