### ISSUE TITLE
Error hooks don't fire on uncaught exceptions

### ISSUE THREAD

**Issue by Bogdanp** [encode/apistar#437]
In 0.4 right now, if a handler raises an exception that's not a standard API Star error, then any registered `on_error` hooks don't fire. Minimal example:

```python
from apistar import App, Route, http, exceptions


def index() -> dict:
    return {}


def fail_1() -> None:
    raise Exception("fail")


def fail_2() -> None:
    raise exceptions.BadRequest("bad request")


class Hook:
    def on_error(self, response: http.Response) -> http.Response:
        print("ON ERROR HOOK WAS CALLED")
        return response


app = App(
    routes=[
        Route("/", "GET", index),
        Route("/fail-1", "GET", fail_1),
        Route("/fail-2", "GET", fail_2),
    ],
    event_hooks=[Hook()]
)


app.serve(host="127.1", port=8000)
```

When you visit `/fail-2` the message gets printed to stdout, but when you visit `/fail-1`, it doesn't.

**Comment by jgirardet** [comment]
that's because `exception_handler` only catch APIstar excepton and raises all others then on_error hooks is not called.
```
def exception_handler(self, exc: Exception):
        if isinstance(exc, exceptions.HTTPException):
            print(exc.detail)
            return JSONResponse(exc.detail, exc.status_code, exc.get_headers())
        raise
```
Maybe we could also catch other exceptions with something like :
 ```
       elif isinstance(exc, Exception):
            return JSONResponse(str(exc), 400)
```

**Comment by rhelms** [comment]
I had extended App to my application specific exceptions

from apistar import App as WSGIApp

class App(WSGIApp):
    def exception_handler(self, exc: Exception):
        if isinstance(exc, WidebandException):
            return JSONResponse(exc.response, exc.status_code)

        return super(App, self).exception_handler(exc)

Because I'm using event hooks to ensure all my requests, responses and errors are logged, it would probably be a good idea to try any unhandled exceptions from the `return super` and return an appropriate JSONResponse so other exceptions get handled too. Thought I'd probably return a 500, as an uncaught error is at least my fault.

**Comment by pslacerda** [comment]
The #443 seems related to this.

**Comment by pslacerda** [comment]
Something like this would do the job and the API would return the right thing. But if the developer hasn't any on_error hook registered he will miss the exception and had no idea of why it is happening. Of course this is his/her fault or a default logging on_error hook could be addded.

```python

class ServerError(HTTPException):
    default_status_code = 500
    default_detail = 'Server error'

def exception_handler(self, exc: Exception) -> Response:
    if isinstance(exc, exceptions.HTTPException):
        return JSONResponse(exc.detail, exc.status_code, exc.get_headers())
    return self.exception_handler(exceptions.ServerError())
```

The next approach ensures that any error on any on_error hook don't prevent other on_error hooks to be called.

```python
except Exception as exc:
            state['exc'] = exc
            for func in self.on_error_functions:  # don't include finalize_asgi
                try:
                    self.injector.run([func], state)
                except Exception as exc:
                    print(exc)  # requires logging
            return self.injector.run([self.finalize_wsgi], state)
``` 

Both approaches are good enough.

Anyway maybe we should place `self.injector.run([self.finalize_wsgi], state)` separated at the end of both success and error to ensure that the start_response of the next middleware is called.

Yet another approach is to require that on_error hooks don't raise exceptions, it is a very good approach but make the error hooks somewhat harder to do right.


```python
except Exception as exc:
                state['exc'] = exc
                try:
                    return self.injector.run([func], state)
                except Exception as exc:
                    import sys
                    return finalize_wsgi_failure(sys.exc_info())
```

**Comment by pslacerda** [comment]
These are only ideias. Probably we just need to return 5xx. And also pass the exc_info forward or show the error, or both.
