### ISSUE TITLE
Type conflicts with typing.Type

### ISSUE THREAD

**Issue by pslacerda** [encode/apistar#441]
As the title says:

```python
from typing import Type
from apistar.types import Type as APIStarType  # unwanted renaming
```

**Comment by tomchristie** [comment]
I’m happy to take suggestions on alternatives, but I’m not *necessarily* going to avoid any names that can also be found elsewhere in the standard library.

**Comment by pslacerda** [comment]
"Model" is a good one, I guess.

This clash is somewhat annoying because APIStar, that is heavily based on typesystem features, clashes with a library of the typesystem.

Seems natural to explore typing features like Type[MyClass] on a module full of typing.

I also liked the 0.3 approach of the root object be an Object instead of a Type on another hierachy, feels more natural and easier. Maybe I'm missing something.
