### ISSUE TITLE
Response component

### ISSUE THREAD

**Issue by pslacerda** [encode/apistar#448]
I want to make an event hook that modify response headers, for this I must override the `render_response` hook. If `Response` was an injectable component this could be done easier. Imagine hooks or components that are expected to be run after the handler to modify the respose.

Today I must implement a new `render_response` that calls the original. So I'm asking for an `ResponseComponent`.

**Comment by tomchristie** [comment]
`response` *is* made available to event hooks, as documented in http://www.encode.io/apistar/api-guide/event-hooks/

However, https://github.com/encode/apistar/pull/451 improves things slightly by making `Response` be a standard component. (And removing the requirement that event hooks return the response instance themselves.)

**Comment by pslacerda** [comment]
Cool!
