### ISSUE TITLE
Can't alter response in event hook

### ISSUE THREAD

**Issue by tino** [encode/apistar#477]
Since #460 I can't return a different response in on_response. I'm trying to add CORS headers like so:
```
class CORSHook:
    headers = {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "*",
        "Access-Control-Allow-Headers": "*",
    }

    def on_response(self, request: http.Request, response: http.Response, exc: Exception):
        if isinstance(exc, exceptions.MethodNotAllowed) and request.method == 'OPTIONS':
            return http.Response('', status_code=204, headers=self.headers)  # <== this does run

        response.headers["Access-Control-Allow-Origin"] = "*"
        response.headers["Access-Control-Allow-Methods"] = "*"
        response.headers["Access-Control-Allow-Headers"] = "*"
        return response
```
Output is still a 405 Method Not Allowed

**Comment by lucianoratamero** [comment]
for CORS, there is the apistar_cors and the apistar_cors_hooks packages (which I've made literally 2 days ago, based on apistar_cors and wsgicors). I didn't have any issues modificating the response headers. could you take a look at it and see if there is any difference in the implementation, please? :)
https://github.com/lucianoratamero/apistar_cors_hooks

**Comment by tomchristie** [comment]
You should mutate the response object, rather than returning a new one.

Any of the following will work.

```
response.content = ...
response.status_code = ...
response.headers = ...
```

You can actually also return a different response if you annotate the event hook with `-> http.Response`, but we're not documenting that at the moment, and I wouldn't rely on it.

**Comment by tino** [comment]
Ah okay. Thanks!

@lucianoratamero thanks, but just those couple of lines will do for me now. No need for another package ;)
