### ISSUE TITLE
Types properties confusion between has_default and allow_null

### ISSUE THREAD

**Issue by jordanambra** [encode/apistar#478]
I am building out nested types and am using validators.Object(allow_null=True) to set properties on a type class. If I create a new instance of the type that uses one of these object validators, it automatically sets the property as one of the required fields, which seems to miss the point of the allow_null parameter.

The code in question where it compiles the list of required fields is here: https://github.com/encode/apistar/blob/0.5.4/apistar/types.py#L38

This calls out to the common validator method has_default, found here: https://github.com/encode/apistar/blob/0.5.4/apistar/validators.py#L54

In order to make this work, I have to set validators.Object(allow_null=True, default=None). Is this intended behavior? I spent quite a long time trying to understand this and tracking it down. It would make more sense to me that if allow_null = True, then it should automatically set default = None or otherwise skip making it a required field.

**Comment by jordanambra** [comment]
BTW, I upgraded to 0.5.7 and appreciate the change to allow for true nested types instead of validators.Object().

**Comment by tomchristie** [comment]
Not necessarily a given that `allow_null=True` ought to set `default=None`, but on balance I think it's almost always what users will actually want, so yup, let's go with this.
