### ISSUE TITLE
on_response hook don't receive the same injected dependency as on_request

### ISSUE THREAD

**Issue by pslacerda** [encode/apistar#490]
Edited on_error -> on_response.

For some reason some objects injected `on_request()` isn't the same injected on `on_response()`, but other components like `WSGIEnviron` are. This happened on an exception context.

```python

class AppOpticsTracerHooks:
    @staticmethod
    def on_request(dependency: Dependency, environ: WSGIEnviron) -> None:
        dependency.attr = 1
        environ['attr'] = 1

    @staticmethod
    def on_response(dependency: Dependency, host: Host,
                 request: Request, response: Response) -> Response:
         # after a exception happened on the handler
         assert environ['attr'] == 1  # ok
         assert dependency.attr == 1  # fails
```

**Comment by pslacerda** [comment]
Seems that for each `injector.run()` a new initial state is provided. Maybe could the state be preserved between `injector.run()` calls in the same `App.__call__()`?

**Comment by pslacerda** [comment]
Forgot the last comment. I have no idea what I was talking about.

I wanted to say to `resolve_functions()` use the actual state together with the initial state if possible. Maybe can this actually improve the performance and fix this issue? Or there are any `Component` that needs to be always reinstantiated?

**Comment by tomchristie** [comment]
> For some reason some objects injected on_request() isn't the same injected on on_response(), but other components like WSGIEnviron are. This happened on an exception context.

I'd consider this a valid bug yup - they ought to get the same state, if it has already been created.

**Comment by pslacerda** [comment]
Seems that it you already fixed it somewhere between this issue and today. `state` is the same between hooks invokations.

https://github.com/encode/apistar/blob/002b525a108a2fa6b63855e2ca0fab7e1909e77b/apistar/server/app.py#L197

**Comment by tomchristie** [comment]
@pslacerda Great, thanks for confirming.
