### ISSUE TITLE
String validator does not work when len(self.enum) == 1

### ISSUE THREAD

**Issue by marekkosta** [encode/apistar#503]
```python
from apistar import validators, types

class Foo(types.Type):
    key = validators.String(enum=['value'])
```
Going then
```python
Foo({'key': 'a'})
```
fails with a KeyError. This is a bug caused by the fact that validators.String type does not contain variable
```python
self.exact
```
needed in the format call of function Validator.error_message. A quick fix could be to simply define self.exact before calling error_message, but I'm not sure whether this would be correct w.r.t. other things.
Therefore this is an issue and not a pull request.

Thank you in advance for fixing this!

**Comment by tomchristie** [comment]
Closed via #590.
Release incoming.
