### ISSUE TITLE
JSON list in request body automatic validation

### ISSUE THREAD

**Issue by jpiorkowski** [encode/apistar#507]
Hello,

Thank you for your incredible work on API Star! We are upgrading from apistar==0.3.9 and have a question I haven't been able to figure out. Any input you might be able to provide would be appreciated.

Is it possible on apistar==0.5.10 to provide a JSON list as the request body to a route handler, and have the handler automatically validate it?

We can read the list from `http.RequestData`, but API Star automatically verifying all items in sub-dictionaries and returning HTTP 400 on validation failure was great.

On apistar==0.3.9, we had roughly the following setup:

```
class Trip(typesystem.Object):
    properties = { 'name': typesystem.String }
    required = ['name']
    # in our actual code, the properties are nested some more

class ListOfTrips(typesystem.Array):
    items = Trip
    min_items = 1

def calculate(verified_trips: ListOfTrips):
    for trip in verified_trips:
        print(trip['name'])

app = App(routes=[
    Route('/calculate', 'POST', calculate)
])
```

Then calling it with `curl -sS -X "POST" -H "Content-Type: application/json" -d '[{"name": "something"}, {"name": "something else"}]' http://localhost:3000/calculate` gave us a correct response.

Calling with a missing field `curl -sS -X "POST" -H "Content-Type: application/json" -d '[{"name": "something"}, {"not_a_name": "something else"}]' http://localhost:3000/calculate` would get an HTTP 400 with an error report: `{"1": {"name": "This field is required."}}`

Is this possible on the newer versions? As far as I can tell, the param definitions have to be `class ListOfTrips(types.Type)`, leaving us with no room to specify a list immediately in the root.

I have tried:

```
class ListOfTripsType(types.Type):
    items = validators.Array(items=Trip, min_items=1)

def calculate(verified_trips: ListOfTripsType):
    ...

# raises apistar.exceptions.ConfigurationError: Cannot use reserved name "items" on Type "ListOfTripsType", as it clashes with the class interface.
```

```
class ListOfTrips(validators.Array):
    items = Trip
    ... etc

def calculate(verified_trips: ListOfTrips):
    ...

# raises apistar.exceptions.ConfigurationError: No component able to handle parameter "verified_trips" on function "calculate".
```

```
def calculate(trips: http.RequestData):
    for trip in trips:
        ...

# works, but I'd have to validate and return HTTP 400 manually
```

I _have_ been able to validate manually, with roughly the same error messages as before, with the following:

```
trips_validator = validators.Array(items=Trip, min_items=1)

def calculate(trips: http.RequestData):
    try:
        validated_trips = trips_validator.validate(trips)
    except exceptions.ValidationError as e:
        return http.JSONResponse(e.detail, status_code=400)
```

but when I try to use it automatically it fails:

```
trips_validator = validators.Array(items=Trip, min_items=1)

def calculate(verified_trips: trips_validator, trips: http.RequestData):
    ...

# raises apistar.exceptions.ConfigurationError: No component able to handle parameter "verified_trips" on function "calculate".
```

Is it possible to do the validation automatically? If it is possible, I would be happy to help improve the docs to point others in the right direction.

If currently not, is it feasible to reintroduce such a functionality in the new versions?

**Comment by freakabcd** [comment]
@chenl TestClient is really a `requests.Session` object. This section is relevant: [More complicated POST requests](http://docs.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests)
The example code you pasted works correctly with a trivial change. Either one of these will do:

- use the `json` argument. `data` will use form-encoding on the dict by default. `json` also sets a `Content-Type: application/json` header
```...
response = client.post('/', json={'arr': ['foo', 'bar', 'baz'],})
```

- encode the data manually
```...
import json
response = client.post('/', data=json.dumps({'arr': ['foo', 'bar', 'baz'],}))
```

**Comment by freakabcd** [comment]
@jpiorkowski This code (checked on 0.5.22) might be helpful to you. It produces the same result as your pasted code with the exception of wrapping the trips array within an object. I prefer this way (keyed toplevel objects) as it means I can add more properties and expect existing code to work without any changes. Essentially
```
{
  trips: [
    {name:trip1},
    {name:trip2}
  ]
}
```
```python
from apistar import App, Route, types, validators
from apistar import TestClient


class Trip(types.Type):
    name = validators.String(min_length=3)


class TripData(types.Type):
    trips = validators.Array(
        items=Trip,
        min_items=1
    )


def calculate(validatedTrips: TripData):
    for trip in validatedTrips.trips:
        print(trip)


def post_request_to_calculate(client: TestClient, json: dict):
    response = client.post('/calculate', json=json)
    print(response)
    if response.status_code != 200:
        print(response.text)
    print(10*'-')


routes = [Route('/calculate', method='POST', handler=calculate)]
app = App(routes=routes)

if __name__ == '__main__':
    client = TestClient(app)
    post_request_to_calculate(client, {
        'trips': [{"name": "something"}, {"name": "something else"}]
    })
    post_request_to_calculate(client, {
        'trips': [{"name": "something"}, {"not_a_name": "something else"}]
    })
```
Output produced:
```
<Trip(name='something')>
<Trip(name='something else')>
<Response [200]>
----------
<Response [400]>
{"trips":{"1":{"name":"This field is required."}}}
----------
```

**Comment by jpiorkowski** [comment]
Thanks @freakabcd. Unfortunately I cannot change the format of the data coming in, it has to be a list as root. The manual validation workaround seems to be working well enough. Perhaps this is too marginal to bother supporting? I don't mind closing the issue if so.

**Comment by jpiorkowski** [comment]
The manual valuation has been working well for us, so this isn't a priority. I will close this issue to avoid accumulating too many low-prio open issues. Thanks again for your work on the framework!
