### ISSUE TITLE
How to get Request as stream?

### ISSUE THREAD

**Issue by Lynskylate** [encode/apistar#514]
Like sanic 
```python
@app.post('/stream', stream=True)
async def handler(request):
    async def streaming(response):
        while True:
            body = await request.stream.get()
            if body is None:
                break
            body = body.decode('utf-8').replace('1', 'A')
            response.write(body)
    return stream(streaming)
```
sorry, but I can't find any support for request stream in document.
In flask or other web framework, request.stream as StreamReader can make us get request data as stream.

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
