### ISSUE TITLE
how to use bootstrap with apistar?

### ISSUE THREAD

**Issue by avonar** [encode/apistar#525]
Hi, i see bootstrap files in repository, what is the best way to make bootsrap project with apistar? May anybody show some example?

**Comment by avonar** [comment]
I trying to start by this guide https://docs.apistar.com/#api-star , but link http://127.0.0.1:5000/docs/ doesnot work

**Comment by dasdachs** [comment]
@avonar could you give more information? How did you start the app?

Regarding **Bootstrap**: including Bootstrap is easy, just include it in your templates. Take a look at examples using `flask` and `jinja2`, e.g. Miguel Grinberg's [Flask Mega tutorial](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xii-facelift)
