### ISSUE TITLE
CLI executable not installed via pip

### ISSUE THREAD

**Issue by aleksarias** [encode/apistar#530]
apistar executable is not installed as part of pip installation on Ubuntu 17 nor Mac OSX 10.13.4 

Issue command : `pip3 install apistar`
Installer runs with no errors. 

Search OS for executable via: `sudo find / -name apistar`
Results only with python module within python3 site-packages. No executable can be found. 

apistar installation info:
```
Name: apistar
Version: 0.5.12
Summary: Blazingly fast & beautifully expressive Web APIs
Home-page: http://www.encode.io/apistar/
Author: Tom Christie
Author-email: tom@tomchristie.com
License: BSD
Location: /usr/local/lib/python3.6/site-packages
```

**Comment by tomchristie** [comment]
There isn't a cli - it's been removed since 0.4.
There is a PR to bring something back in... https://github.com/encode/apistar/pull/521

**Comment by aleksarias** [comment]
Thanks Tom! Sorry about that.
