### ISSUE TITLE
Minor docs UI improvements

### ISSUE THREAD

**Issue by brennv** [encode/apistar#541]
Could we:

- Enable highlight.js for code samples #538
- Normalize docs UI fonts #539

And maybe:

- Expose the docs UI title for customization #540

**Comment by tomchristie** [comment]
Should be doing some work on the docs theming this Thursday, along with @alpower.
I'd suggest we leave any PRs there on hold for now until we get that work out.

Thanks! 😄

**Comment by brennv** [comment]
Cool cool, I'll close all those for now to reduce the clutter.
