### ISSUE TITLE
is this a bug?

### ISSUE THREAD

**Issue by jianjianzhu** [encode/apistar#543]
![image](https://user-images.githubusercontent.com/38814264/40052219-f3459f52-586f-11e8-9ced-e5677a4f9e1d.png)
got an error where  visit localhost:5556/docs
Could not build url for endpoint 'static' with values ['filename']. Did you mean 'serve_static_asgi' instead?
**and i find self.map._rules_by_endpoint not contain the key of static**
![image](https://user-images.githubusercontent.com/38814264/40052496-9aaa19ee-5870-11e8-8cfe-880fa6f3b446.png)

**Comment by audiolion** [comment]
there are a few open prs that address this issue

**Comment by jianjianzhu** [comment]
I solved this problem by add same codes   to the app.py. /usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/apistar/server/app.py
![image](https://user-images.githubusercontent.com/38814264/40057411-d46aa0da-5880-11e8-9d58-6c450beee7e2.png)

**Comment by tomchristie** [comment]
@audiolion Which should I be looking at?
