### ISSUE TITLE
schema endpoint incorrectly build paths when using Include

### ISSUE THREAD

**Issue by androiddrew** [encode/apistar#544]
Hi just loaded up 0.5.18 and went to go check out the http://localhost:5000/schema/ response. Looking through the result I see:

```
        "/auth/auth/login": {
            "post": {
                "tags": [
                    "auth"
                ],
                "operationId": "login"
            }
        },
```

Where I am using `Include('/auth', name='auth', routes=routes)` in my code.  I believe this is a bug.

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
