### ISSUE TITLE
Error when creating custom validation on the Type System

### ISSUE THREAD

**Issue by jonatasbaldin** [encode/apistar#547]
Hello there!

The documentation states that, to create a custom validation on a Type, one should:

```python
class Organisation(types.Type):
    is_premium = validators.Boolean()
    expiry_date = validators.Date(allow_null=True)

    def __init__(self, *args, **kwargs):
        value = super().__init__(*args, **kwargs)
        if value.is_premium and value.expiry_date is not None:
            message = 'premium organisations should not have any expiry_date set.'
            raise exceptions.ValidationError(message)
        return value
```

I tried it, but `value` is empty since the parent `__init__` does not return anything (and I think it shouldn't anyway, considered an [anti-pattern](https://docs.quantifiedcode.com/python-anti-patterns/correctness/explicit_return_in_init.html)).

To solve it, I just called the parent `__init__` and validated the field using `self`, still not returning anything.

```python
class Organisation(types.Type):
    is_premium = validators.Boolean()
    expiry_date = validators.Date(allow_null=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.is_premium and self.expiry_date is not None:
            message = 'premium organisations should not have any expiry_date set.'
            raise exceptions.ValidationError(message)
```

And it worked perfectly 🎉

Is this a correct way to validate? Am I missing something?

Thanks!

**Comment by bryanapperson** [comment]
I also encountered this issue @tomchristie any feedback on this? It seems like the documentation is incorrect.

**Comment by tomchristie** [comment]
Now redundant, given https://github.com/encode/apistar/pull/649
