### ISSUE TITLE
Type annotation not reflected on the docs

### ISSUE THREAD

**Issue by jonatasbaldin** [encode/apistar#548]
Hello there!

The return annotation type is reflected on the Schema, but not on the Docs.

Here's my type:
```python
class User(types.Type):
    id = validators.Integer()
    username = validators.String(max_length=100)
```

Here's the endpoint:
```python
def list_users() -> typing.List[User]:
    return Users.all()  # returns a list of Users
```

Here's the schema (partial):
```
"/users/": {
    "get": {
        "operationId": "list_users",
        "responses": {
            "200": {
                "description": "",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/components/schemas/User"
                            }
                        }
                    }
                }
            }
        }
    },
```

Here's the docs:
![image](https://user-images.githubusercontent.com/8570364/40165227-100a311a-59d9-11e8-982d-af998fcd3f45.png)

Is this the normal behaviour? Should the docs include something about the return data using the given Type?

Thanks!

**Comment by tomchristie** [comment]
Correct: Response schemas aren't yet rendered in the docs.
Yup - it'll come.

**Comment by jonatasbaldin** [comment]
Ok, will watch the PRs to see it coming!

Thanks!
