### ISSUE TITLE
async, can't POST data

### ISSUE THREAD

**Issue by Blekely** [encode/apistar#581]
Using the code below, the program just hags while either doing a POST or GET request.
I suspect `http.Body` is the culprit as it also hags.
using 0.5.30
```
from apistar import ASyncApp, Route, types, validators, http

class PostData(types.Type):
    data = validators.String()

async def get_data(request: http.Request) -> dict:
    print(request)
    return {'data': 'success'}

async def post_data(data: PostData) -> dict:
    print(data)
    return {'data': data.data}

routes = [
    Route('/', method='GET', handler=get_data),
    Route('/', method='POST', handler=post_data),
]

app = ASyncApp(routes=routes)

if __name__ == '__main__':
    app.serve('127.0.0.1', 5000, debug=True)
```

**Comment by songww** [comment]
![default](https://user-images.githubusercontent.com/8115960/41136190-b399a092-6b07-11e8-974e-fc47caaf6a2c.png)

**Comment by Blekely** [comment]
thanks songww, 
Yes, just tried that and it does indeed work.
But running `python test.py` does not.
Is using uvicorn the preferred way to run async?

**Comment by songww** [comment]
You can see #489  and #501.

**Comment by Blekely** [comment]
Ah ok. thanks. will close.
