### ISSUE TITLE
How the amazing type system feature will be integrated with other frameworks after v0.6?

### ISSUE THREAD

**Issue by tongda** [encode/apistar#627]
I like the type system very much, but it seems there will be no server side support since v0.6. What is the future plan of this amazing feature?

**Comment by tongda** [comment]
I understand.

I think I would prefer to 2nd option:
> Use the typesystem stand-alone, and support having that generate schema definitions for the types, but don't automagically infer anything else.

From my perspective, type validation and auto schema generation seems to be a must-have feature and it would be very cool to be framework agnostic. On the other hand, DI is a nice-to-have feature to make code looks clean and fancy.

**Comment by auvipy** [comment]
I would be really happy to see them in with starlette...

**Comment by Dopebiz6Dime** [comment]
I think I might have a solution with this .. I’m working on something very similar now

**Comment by lucianoratamero** [comment]
there's already this ongoing effort to couple it with starlette, so give it a look :]
https://github.com/PeRDy/starlette-api

**Comment by tiangolo** [comment]
Hey guys, I built something based on Starlette, heavily inspired by APIStar ([I like to consider it a "spiritual successor" to APIStar](https://fastapi.tiangolo.com/alternatives/#apistar-05)).

You can define path, query, cookie and header parameters using types. The same for body requests, including deeply nested schemas, using Pydantic models. All is based on Python type hints, so you get autocomplete everywhere.

It has a dependency injection system, several security tools, all based on OpenAPI 3 (with automatic schema generation), including 2 different interactive API documentation web UIs, etc.

You might want to check it: https://github.com/tiangolo/fastapi

**Comment by tomchristie** [comment]
Closing, given https://github.com/encode/apistar/pull/649 - The type system is now a properly independant package.
