### ISSUE TITLE
Schema Generator ABC (or interface)

### ISSUE THREAD

**Issue by carltongibson** [encode/apistar#640]
DRF has schema generators. Starlette has schema generators. It would be nice if APIStar provided an ABC (or protocol or interface) that we could follow there (or anywhere). 

e.g. Methods like `get_path_parameters()` should be more or less standard. 

It might be that this could just be a documentation thing: I may not want to import APIStar just for an ABC.

**Comment by tomchristie** [comment]
Sorry you'll have to expand on this for me.

**Comment by carltongibson** [comment]
Don't worry: Starlette schema generation is not similar enough to DRF's to warrant this: ends up reducing to "c.f. OpenAPI Docs". If things evolve differently I'll come back to it. Sorry for the noise.
