### ISSUE TITLE
Apistar Project Status

### ISSUE THREAD

**Issue by arvinsim** [encode/apistar#644]
I am not sure what the state of APIStar is(frozen? discontinued?)

I am taking over a project that uses APIStar. I look over the documentation and it seems to be a mess. Incomplete documentation, no beginner tutorial. I just wanted to create an openapi schema and I don’t know if I should use schema.yml, schema.yaml or schema.json!

It would help me immensely if I have insight in what the current state of the project is so that I can evaluate if I should continue using it or look into alternatives(like Starlette).

**Comment by tomchristie** [comment]
It's not my top priotity at the moment, but I do plan on coming back to it.

> I just wanted to create an openapi schema and I don’t know if I should use schema.yml, schema.yaml or schema.json!

See http://docs.apistar.com/schema-validation/

You can call the schema whatever you want.
Use: `apistar validate --path schema.yaml --format openapi` to validate it.

> I am taking over a project that uses APIStar.

I *guess* you mean API Star server, which is discontinued. http://docs.apistar.com/#where-did-the-server-go

**Comment by arvinsim** [comment]
Got it. Thanks for the prompt reply.
