### ISSUE TITLE
tests improvements

### ISSUE THREAD

**Issue by amenezes** [encode/apistar#673]
Hello all,

I noticed that apistar is compatible, at first, with python 3.8 and pypy would not be useful include this in the tests, for example, in a [tox.ini](https://tox.readthedocs.io/en/latest/) file and also update the metadata?

Another two issues are relative to:
- include [branch](https://en.wikipedia.org/wiki/Code_coverage#Basic_coverage_criteria) on the tests report;
- and if there is some sense in include [tests directory](https://github.com/encode/apistar/blob/master/scripts/test#L10) on the test [coverage](https://travis-ci.org/encode/apistar/jobs/648346802#L309)?

It's relevant submit a PR with this improvements?

**Comment by tomchristie** [comment]
I'd prefer any changes here to be kept minimal.
Yup we could accept 3.8 being added to the test matrix.
Yup it's reasonable to include the tests directory in coverage.

Any pull requests here should address a single issue at a time.

Thanks!
