### ISSUE TITLE
Schema validation & annotation

### ISSUE THREAD

**Issue by tomchristie** [encode/apistar#70]
We have some of this in place at the moment, but we still need:

- [x] Object
- [x] Array
- [x] Enum
- [x] Documentation
- [x] Defaults on schema types.
- [x] Nullable

Plus a whole bunch of finessing around things like:

* Keyword defaults on handler functions.
* Support `List` in handler input types.
* Coerce primitive types to schema types? (eg. `bool` then handles "True"/"False" string literals, `str` then trims whitespace by default.)
* Returning aggregated validation errors for multiple parameters.
* Which typing annotations we support in views.
* Native formats such as `datetime` that have a string serialization.
* If we want to constrain the typing system against GraphQL, eg. no general "Map" type.

**Comment by ddorian** [comment]
... why not just use marshmallow ? Aren't you doing too much this way (like django with friends) ? 
The same for swagger etc.

**Comment by tomchristie** [comment]
@ddorian We can't use marshmallow (or any other existing library) here because they wouldn't fulfil our design criteria of:

* Actual type subclasses, that we can then validly use as type annotations.
* 1:1 mapping onto JSON Schema.

**Comment by thedrow** [comment]
May I suggest [PyDantic](https://github.com/samuelcolvin/pydantic)?
It supports type annotations out of the box and [type subclasses](https://pydantic-docs.helpmanual.io/#recursive-models).
It's pretty young but so is APIStar so it's still a good opportunity to switch.

**Comment by hsharrison** [comment]
Is there any movement on Nullable? Or is there a workaround? I'm trying to setup apistar with SQLAlchemy and I get validation errors when `None` is passed to a schema, even if there is a default. I can't figure out any way to make it work.

**Comment by tomchristie** [comment]
Not yet, tho certainly on the immediate roadmap yup.
Sketching out next steps, here... https://github.com/encode/apistar/projects/1

**Comment by kianxineki** [comment]
required will be a future argument?

**Comment by tomchristie** [comment]
Most likely that, or something similar yes, but needs some thinking about first.

**Comment by 7robertodantas** [comment]
Is there any way to define a schema property as read only? I am needing that to use in a property like 'id', to prevent user send an id in a create / post method.

**Comment by pslacerda** [comment]
APIStar is a very enjoyable framework with a lot of nice ideas.

@thedrow I just made a library to APIStar use PyDantic as typesystem. Seems fine to me, I really liked it.

`Enum` and `list` needs more testing. `Optional` (or nullable) , `Union` and recursive models support aren't done yet.

Maybe you should use `Optional` for nullable fields, but maybe is better to add `Object(nullable=True)` as it look less ugly.

Keep the good work!

**Comment by viking** [comment]
Any plans yet to add a way to make a field be required? I've tried `typesystem.string(min_length=1)` and it seems to allow missing a field.

**Comment by viking** [comment]
Aha, I found the `required` option for `typesystem.Object`.

**Comment by zywind** [comment]
Any progress on supporting nullable? typesystem.Object would become really useful with it.

**Comment by robertorobles** [comment]
Will it be possible to use `Union` as a type?
