### ISSUE TITLE
Graph QL

### ISSUE THREAD

**Issue by tomchristie** [encode/apistar#72]
We oughta be able to route GraphQL endpoints to handlers.

We'd want a GraphQL query component that expresses the parameters of the query being made, and there's some considerations to play into our schema type system (eg. how we treat defaults and emptyness)

**Comment by rcshubhadeep** [comment]
So, is there a plan to use - http://graphene-python.org/ ?

**Comment by tomchristie** [comment]
Unlikely.

**Comment by esistgut** [comment]
Do you have an ETA for this?

**Comment by tomchristie** [comment]
No

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
