### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by tomchristie** [encode/apistar#73]
In the same way that Django REST framework provides an admin style interface on the API.
Would like to do something similar with API Star, in a way that we have a nice admin interface, but without being coupled to a particular backend.

**Comment by penny-api** [comment]
In the project I am working on, my plan is to use Django ORM with apistar and then a modified wagtail admin tooling for back-office admin functions.

My mental model is that admin goes with models and browsable APIs go with APIs and the effort for apistar should go into making the browsable API as feature complete/rich as possible.

I guess this is a down vote, but only relative to other ideas. Great project thus far Tom!

**Comment by tomchristie** [comment]
This one is still a way off, but fairly clear to me how it'll all fit in.

For what it's worth "run inside Django" and "run inside Flask" *are* both things on the roadmap, which might be relevant to you.

Curious to see more about what you're working on! 😝

**Comment by erik-sn** [comment]
Is this something you imagine being inside the framework, or an external package that can be installed? I'm toying around with a prototype that, hypothetically, would be an external package.

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
