### ISSUE TITLE
Django ORM backend

### ISSUE THREAD

**Issue by tomchristie** [encode/apistar#75]
At some point I'd like to see us bring in a Django ORM backend that provides the functionality of the ORM and migrations framework. The developer productivity that Django brings there is pretty awesome, and I'd really like to see both this *and* SQLAlchemy be valid options.

**Comment by ahopkins** [comment]
I am working on a backend for [peewee ORM](http://docs.peewee-orm.com/en/latest/peewee/quickstart.html). I see now that the implementation for SQLAlchemy is rather hardcoded in. To abstract this away, I am going to work on adjusting the `App` class to accept a database backend (somewhat similar in theory to the way Django operates), with the existing `SQLAlchemy` object as the default. Anyone else working on something like this?

**Comment by tomchristie** [comment]
Linking to the follow-up to @ahopkins comment... https://github.com/tomchristie/apistar/pull/138

**Comment by ofpiyush** [comment]
@tomchristie can we release a version with this?

**Comment by tomchristie** [comment]
@ahopkins As of the 0.2 release we've now removed any hardcoded-ness for components.
@ofpiyush Yup, all in now.
