### ISSUE TITLE
Websockets support

### ISSUE THREAD

**Issue by tomchristie** [encode/apistar#76]
Requires either of #29, #9 first.

Client side support for live endpoints with content-diffs.
Support for notifications of updating live endpoints.

**Comment by jeamland** [comment]
Along the lines of h11 and h2: https://github.com/python-hyper/wsproto

**Comment by maziarz** [comment]
What would be the short term solution to this feature?

**Comment by ckcollab** [comment]
@maziarz ..if you still are interested: you could probably just do a long polling/streaming response?

**Comment by tino** [comment]
What is currently blocking this? Or what is required? Both #9 and #29 are closed.

**Comment by extraymond** [comment]
It seems that uvicorn now accepts websockets response, would be nice to let apistar handle websocket too.

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
