### ISSUE TITLE
Auth & Permissions

### ISSUE THREAD

**Issue by tomchristie** [encode/apistar#78]
Right now authentication and permissions have to be handled as custom components or inside the view handler. We'll want to provide some out of the box options here, such as JWT.

**Comment by maziarz** [comment]
+1 for [oauthlib](https://github.com/idan/oauthlib) integration

**Comment by piotr-szpetkowski** [comment]
I'd be interested in [python-jose](https://github.com/mpdavis/python-jose)

**Comment by tomchristie** [comment]
Good pointers, thanks folks!

**Comment by maziarz** [comment]
I am very curious about the Permissions part as i have been experiencing quite many different approaches from the JS world, where ACL's are very common and combined with Role assignments.

**Comment by tomchristie** [comment]
@maziarz Don't expect us to present anything super-abstracted at this point. Decisions about 'roles' and permission levels are likely to be left in application land - we'll just be making sure that there's a good general purpose answer to applying whatever kind of policy you do want either on a global or a per-view level.

**Comment by maziarz** [comment]
I nearly forgot sessions..

**Comment by audiolion** [comment]
Was this addressed in the 0.2.0 release? I am hitting this point right now where I will be calling the same function at the start of every view function to check a JWT for authorization and handling before proceeding, I can build my own JWT component but I wanted to ask here first if maybe its something that I should just be helping build into the library with a PR.

Do you know what you are looking for in a JWT handler implementation? I am assuming a component that uses the `pyjwt` library to encode and decode, basing its secret on an apistar setting the user sets and throwing an exception on import if the user hasn't defined the setting.

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
