### ISSUE TITLE
Browsable API

### ISSUE THREAD

**Issue by tomchristie** [encode/apistar#80]
Because, well, y'know.
It's kinda our baby.

**Comment by piotr-szpetkowski** [comment]
Will apistar provide root view by default?

**Comment by tomchristie** [comment]
No, we won't be providing any automagic views, at least to start with, but we might want to provide an *documented example* of how a user would create a root view themselves, with hyperlinks to various other places in the API.

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
